### ISSUE TITLE
Data Attributes stopping touch scrolling

### ISSUE THREAD

**Issue by MattPostlethwaite** [glidejs/glide#140]
I have run into a touch scroll issue with data attributes. 

When I create a custom external menu which is full viewport width, as follow:
`<div data-glide-trigger="#Glide_home" data-glide-dir="=2">Go to slide 2</div>`

I'm unable to scroll on a touch devices when dragging on these buttons. After removing the attributes I can scroll again.

I need to use these attributes in this project, so after looking at the glide.js code for this attribute I found that removing preventDefault from this block enabled touch scrolling again:

```
    /**
     * Hande trigger event
     * @param  {Object} event
     */
    Module.prototype.handleTrigger = function(event) {
        event.preventDefault();

        var targets = $(this).data('glide-trigger').split(" ");

        if (!this.disabled) {
            for (var el in targets) {
                var target = $(targets[el]).data('glide_api');
                target.pause();
                target.go($(this).data('glide-dir'), this.activeTrigger);
                target.play();
            }
        }
    };
```

Great work with this slider btw.

**Comment by jedrzejchalubek** [comment]
Yeah, you right. `preventDefault` is great if custom trigger is something small (button), but in your case it will disturb.

I really love solution in Vue, maybe I will adapt this in here.
- `data-glide-trigger="#Glide"` dont prevent events
- `data-glide-trigger.prevent="#Glide"` prevent events

**Comment by MattPostlethwaite** [comment]
That sound like a good idea. Give the user more control and further customisation.

**Comment by jedrzejchalubek** [comment]
Version 3.0.0 is coming. Feature requests for version 2.0 are suspended. Closing, sorry.
