### ISSUE TITLE
Fade and flashing issue

### ISSUE THREAD

**Issue by parhs** [glidejs/glide#149]
Hello

Currently when fading there is a flashing issue which is annoying. It seems it happens because both images become semitransparent and blend with background.  
I did change code at animation module and seems that it works fine. Please let me know if there is a way to change this behavior without changing Glide code. 

```
    Module.prototype.slideshow = function() {

        if (typeof Glide.previous !== 'undefined') {
          // Set previous slide on top and hide others
          Glide.slides.css('transition','');
          Glide.slides.not(Glide.previous-1)
                      .css('opacity',0)
                      .css('z-index',0);
          Glide.slides.eq(Glide.previous-1)
                      .css('opacity',1)
                  //  .css('z-index',0);
          // Force css reflow in order to skip transition for z-index
          Glide.slides.eq(Glide.current-1)
                      .css('z-index',2)
                      .get(0).offsetHeight;
          // Show current slide
          Glide.slides.eq(Glide.current-1)
                      .css('transition', Core.Transition.get('opacity'))
                      .css('opacity', 1);
        }
        Glide.previous = Glide.current;
    };

```

**Comment by jhenderson** [comment]
I just came across this issue on my site today. Hope this can be resolved soon. Thanks.

@parhs your workaround works but the arrows don't show. Interesting solution nonetheless.

**Comment by parhs** [comment]
Maybe I missed something because I didn't need arrows. However I did switch to http://idangero.us/swiper/#.WJA1I7Z957M with no issues so far.
