### ISSUE TITLE
Responsive paddings

### ISSUE THREAD

**Issue by Tomgroot** [glidejs/glide#178]
With a high value for "paddings", the slider looks perfect in only one situation. As you make your screen width smaller, the paddings stay the same and the glide__slide divs become very small.

Is there a way to make responsive paddings, that change regarding the screen width? 

A simple solution like giving the glide_slide a min-width will also solve the problem temporarily

**Comment by jedrzejchalubek** [comment]
Introduced with [`v3.0.0`](https://github.com/glidejs/glide/releases/tag/v3.0.0) release :)

Use `breakpoints` option when initializing glide. Example:

```js
new Glide('.glide', {
  peek: 100,
  breakpoints: {
    800: { peek: 50 },
    480: { peek: 25 },
  }
}).mount();
```
