### ISSUE TITLE
How to dynamically change the direction of transition from right to left

### ISSUE THREAD

**Issue by noorullah-noori** [glidejs/glide#186]
i want to change the transition of carousel from left to right when my language is arabic so how can i do this.

**Comment by noorullah-noori** [comment]
i want to change the transition of carousel from left to right when my language is arabic so how can i do this.

**Comment by jedrzejchalubek** [comment]
RTL is currently not supported by this slider. Sorry.

Gonna mark it as a feature for the next minor version of the slider.

**Comment by noorullah-noori** [comment]
ok thanks but how could we know that the this feature is added

**Comment by noorullah-noori** [comment]
Dear Jędrzej Chałubek,

Hope you have a great day, when i can find my answer about the carousel.

**Comment by jedrzejchalubek** [comment]
Introduced with [`v3.0.0`](https://github.com/glidejs/glide/releases/tag/v3.0.0) release :)
