### ISSUE TITLE
Keep last item fixed on the right edge

### ISSUE THREAD

**Issue by JFonsecaSpot** [glidejs/glide#195]
When navigating and selecting the last item, keep the last item positioned on the right side of the glider.

![image](https://user-images.githubusercontent.com/37213133/38303255-6af33d86-37fd-11e8-8480-9a163b58d3c9.png)

Currently selecting the last item gives you this.

![image](https://user-images.githubusercontent.com/37213133/38303310-963105d2-37fd-11e8-92f3-aaec81416ae7.png)

It would be an improvement if it resulted in this state:

![image](https://user-images.githubusercontent.com/37213133/38303336-b2b974fa-37fd-11e8-990a-6c4fed3f6335.png)

**Comment by Djules** [comment]
+1

**Comment by Abby805** [comment]
+1

**Comment by Abby805** [comment]
Has anyone found a good workaround for this? I love everything else about this library, but this is a dealbreaker for my design team, unfortunately.

**Comment by jedrzejchalubek** [comment]
Just introduced new `bound` option for this feature with https://github.com/glidejs/glide/commit/12928dfce7e32ef70ac1452a2f3fdaa660d7fb23. Would be great if anyone take it for a test run :)

**Comment by EnslavedEagle** [comment]
@jedrzejchalubek It works great, although I think it gives an unexpected outcome when the number of items in slider is less than perPage.

![kitties1](https://user-images.githubusercontent.com/10709214/42205690-6f7aa4ea-7ea5-11e8-88ef-11a500eb2072.jpg)

I would expect the slider to be "draggable" but leave the slides intact, but the outcome is as on following screen:
![kitties2](https://user-images.githubusercontent.com/10709214/42205682-6b1cfc72-7ea5-11e8-9dba-c70617e6b307.jpg)

**Comment by EnslavedEagle** [comment]
@jedrzejchalubek I made a quick fix for that, but I can't really tell how proper that is in the scope of whole script:

```
        define(Run, 'length', {
            /**
             * Gets value of the running distance based
             * on zero-indexing number of slides.
             *
             * @return {Number}
             */
            get: function get() {
                var settings = Glide.settings;

                var length = Components.Html.slides.length;

                if (settings.perView > length) return 0;

                if (Glide.isType('slider') && settings.bound) {
                    return length - 1 - (toInt(settings.perView) - 1) + toInt(settings.focusAt);
                }

                return length - 1;
            }
        });
```

**Comment by jedrzejchalubek** [comment]
`bound` option has been introduced with [`v3.2.0`](https://github.com/glidejs/glide/releases/tag/v3.2.0) release
