### ISSUE TITLE
Can I make a continuously sliding/moving carousel?

### ISSUE THREAD

**Issue by ghost** [glidejs/glide#198]
Hello,

First thank for the plugin.
Is there any solution to use autoplay without pause on each item?

Thank you.

**Comment by jedrzejchalubek** [comment]
Don't know what effect you want to achieve, but you may try setting up `autoplay` option to some really low number.

```js
new Glide('.glide', {
  autoplay: 1
});
```

**Comment by costaweb** [comment]
Thank you for your reply, what I'm trying to achieve is something like this:
https://codepen.io/team/css-tricks/pen/gamYOy

**Comment by jedrzejchalubek** [comment]
Actually, Glide.js was not intended to making something like this. However, with specific options configuration, you may achieve a similar effect: https://codepen.io/jedrzejchalubek/pen/jxEWdg

```js
new Glide('.glide', {
  type: 'carousel',
  autoplay: 1,
  animationDuration: 3000,
  animationTimingFunc: 'linear',
  perView: 3
}).mount()
```

**Comment by anobjectn** [comment]
After reading this I actually wanted to look for performant special purpose libraries/tools/patterns for the continuous repeating horizontal crawl, like the OP imagined. Can anyone share any examples?
