### ISSUE TITLE
Can I run multiple sliders with same classname?

### ISSUE THREAD

**Issue by heliomsolivas** [glidejs/glide#202]
How can I do it? I need to run multiple sliders with class .glide

```
var glide = new Glide('.glide', {
            gap: 15,
        })

        glide.mount();
```

**Comment by jedrzejchalubek** [comment]
You can run a loop over HTMLCollection.

```
var sliders = document.querySelectorAll('.glide');

for (var i = 0; i < sliders.length; i++) {
  var glide = new Glide(sliders[i], {
    gap: 15,
  });
  
  glide.mount();
}
```

**Comment by equinusocio** [comment]
Or using forEach:

```js
const sliders = document.querySelectorAll('.glide')

/**
 * Init the JS component on each reference
 */
component.forEach(item => {
  new Glide(item, {/* conf */}).mount()
})
```

**Comment by dinko** [comment]
Thx, @equinusocio. Just a small fix: I think `component` should be `sliders`.

**Comment by ali-rival** [comment]
`const carousels= document.querySelectorAll(".carousel");

    Object.values(carousels).map(carousel => {
      new Glide(carousel, this.options).mount();
    });`

**Comment by JamieBohannaWebDev** [comment]
@ali-rival 's solution works well for me, but be aware that:

`
Object.values(carousels).map(carousel => {
      new Glide(carousel, options).mount();
});`

[is not supported in IE11.](https://caniuse.com/#search=object.values).

I added Babel to my project however, and this makes it okay again :-)

**Comment by oscarcontrerasnavas** [comment]
What if each slider needs different options?

**Comment by jedrzejchalubek** [comment]
> What if each slider needs different options?

You can hold options in data-attr and parse it using `JSON.parse()` like so:

```html
<div class="glide" data-glide='{
  "loop": true,
  "perView": 3,
  "perMove": 3,
  "perSwipe": 3
}'>
```

```js
const COMPONENT_NAME = "data-glide";
const COMPONENT_SELECTOR = `[${COMPONENT_NAME}]`;

const components = document.querySelectorAll(COMPONENT_SELECTOR);

for (let i = 0; i < components.length; i++) {
  const options = JSON.parse(
    components[i].getAttribute(COMPONENT_NAME) || "{}"
  );

  let glide = new Glide(
    components[i],
    options
  );

  glide.mount();
}
```

**Comment by melvinwang44** [comment]
> You can run a loop over HTMLCollection.
> 
> ```js
> var sliders = document.querySelectorAll('.glide');
> 
> for (var i = 0; i < sliders.length; i++) {
>   var glide = new Glide(sliders[i], {
>     gap: 15,
>   });
>   
>   glide.mount();
> }
> ```

I would like to use multiple gliders, could you assist to provide complete code to use? I'm a self-learn coder so i need some help. Below is the code im using
`<script>
window.addEventListener('load', function(){

new Glider(document.querySelector('.glider'), {
  slidesToShow: 1.3,
	slidesToScroll: 1,
  dots: '#dots',
  arrows: {
    prev: '.glider-prev',
    next: '.glider-next'
  }
  })
})
</script>`

This is [the test page](https://rakanda.kawanelite.com/test/)
