### ISSUE TITLE
"Root element must be a existing Html node"

### ISSUE THREAD

**Issue by krishaamer** [glidejs/glide#204]
Hi @jedrzejchalubek thanks for the awesome plugin! I'm trying to make the new 3.0 version work with Meteor.js however it seems I have some trouble attaching to the html. Do you have any advice?

```
import Glide from '@glidejs/glide';

Template.mytemplate.onRendered(() => {

	let self = Template.instance();
  	new Glide(self.$('.glide')).mount();
});
```

Leads to..
`"Root element must be a existing Html node"`

**Comment by jedrzejchalubek** [comment]
There is an jQuery wrapped object under property `self.$('.glide')` (I'm not familiar with meteor)? 

If so you have to get actual HTML Element by using [`self.$('.glide').get(0)`](https://api.jquery.com/get/) or `self.$('.glide')[0]`.
