### ISSUE TITLE
Error in documentation regarding controls?!

### ISSUE THREAD

**Issue by ralphwetzel** [glidejs/glide#209]
It took me a while to get it, but there seems to be an error in the documentation regarding the setup for controls. The docs tell us to use this syntax to enable controls:

<img width="941" alt="image" src="https://user-images.githubusercontent.com/16342003/39267929-9dda3510-48ce-11e8-8662-c1a355b7860b.png">

There are yet no class definitions for `glide__arrow--prev` or `glide__arrow--next` & thus the positioning of the controls fails.

Use `glide__arrow--left` and `glide__arrow--right` instead to get the intended result...

R.

**Comment by jedrzejchalubek** [comment]
You don't gave us details about your setup, so I'm guesing that you only included core styles.

Library styles are divided into two files:
- `glide.core` - only required styles for proper functioning
- `glide.theme` - optional visual styles that give a look

Controls positioning are a visual styling, so they aren't included in the core styles. So yeah, if you only including core styles, controls will not be positioned.

**Comment by ralphwetzel** [comment]
Your comment might be correct concerning the general usage of `glide.theme`.
Yet even with `glide.theme.css` included, the classes to position the controls are named as I stated ... and not as shown in the documentation.

Refer to your code for verification:
https://github.com/glidejs/glide/blob/66cb09d501d96da68fc7b3e81b32ee9c4b56b35e/src/assets/sass/glide.theme.scss#L31-L37
There are no classes named `glide__arrow--prev` or `glide__arrow--next`...

**Comment by jedrzejchalubek** [comment]
Ah, I overlooked to change that in docs. @mvdnbrk corrected this with https://github.com/glidejs/docs/pull/2 👏
