### ISSUE TITLE
Sizes.width uses root width

### ISSUE THREAD

**Issue by djgadd** [glidejs/glide#210]
Sizes sets the width as `Components.Html.root.offsetWidth`, is that right or should it be using `Components.Html.track.offsetWidth`? `Sizes.width` is used to calculate `Sizes.slideWidth`, in my case my track isn't the same width as the root container, so it's messing up the slide widths.

By the way, awesome work, the components have made it really easy to extend and fit my use case 🎉

**Comment by dp-thomas** [comment]
I also came across this issue. For example, when control arrows shall be placed right and left beneath visible slides. When I apply fix mentioned above, `track`-Element will respond correctly to its available width!

Other than that, working with `Glide` is really nice! 🎊 Thanks for that

**Comment by jedrzejchalubek** [comment]
Could someone prepare a demo that illustrates the problem? It may be a breaking change so I need to be sure if understanding the problem correctly.

**Comment by dp-thomas** [comment]
Hi, thanks for your quick reply. Unfortunatly, I´ve no time to set up a fiddle atm, but I´ll give another try to make my problem more clear:

If I add a horizontal padding ( `e.g. 0 50px` ) to the `HTML Element` with which I invoke `Glide`, a carousel with multiple visible slides per view  won´t calculate each slides width properly anymore.

Like I said, if i apply  the fix from the first comment, it seems to work. But if you say this might cause breaking changes, maybe there´s  a better workaround

**Comment by wc-matteo** [comment]
Same problem here...

**Comment by consulting-jimmy** [comment]
Hi, @jedrzejchalubek I have the same problem as @djgadd, I need to put arrows arround the track element : "outside" the slider, not over.  
In the Sizes component slideWidth is calculate using the root element outerWidth and not the track element width (innerWidth will be better, like that we could set borders and padding to the track element). 

@ghost
> I also came across this issue. For example, when control arrows shall be placed right and left beneath visible slides. When I apply fix mentioned above, `track`-Element will respond correctly to its available width!
> 
> Other than that, working with `Glide` is really nice! 🎊 Thanks for that

How did fix it please ? :)

Here a codesandbox exemple to illustrate the issue
https://codesandbox.io/embed/tender-moser-sx2iq?fontsize=14

Thanks

**Comment by abstractpenguin** [comment]
I can confirm that replacing `Components.Html.root.offsetWidth` with `Components.Html.track.offsetWidth` fixed the issue for me so I could position the next/left arrows to the right/left of the track while still having the slide widths and peek offsets work properly. Thanks, @djgadd!

**Comment by boboldehampsink** [comment]
This seems to be working!

**Comment by aaaatpdev** [comment]
Could [this answer](https://github.com/glidejs/glide/issues/391#issuecomment-521933826) be a workaround?

**Comment by mihalikv** [comment]
Hi @jedrzejchalubek
Here is simple example: http://jsfiddle.net/adscqwho/2/
Use-case is when you want to have arrows "outside" of slider  container.
![image](https://user-images.githubusercontent.com/10236315/91978656-cb155580-ed24-11ea-8bd0-532c3f881976.png)
It can be done by own buttons with some custom JS as proposed [here](https://github.com/glidejs/glide/issues/391#issuecomment-521933826) or maybe with some extra css but I don't found easy and elegant solution for that. But if it won't break anything you can look at https://github.com/glidejs/glide/pull/473/files. 

Thank you for awesome lib.

**Comment by dogooddesignco** [comment]
I was running into this issue also and thanks to the suggestion of manually triggering `go()` I was able to fix it. My code is below. Note that I needed support for multiple glides on a given page, so I iterated through every glide. I then used a somewhat hackish `parentnode.parentnode.parentnode` to select the correct parent of the glide which has an ID. This works in my case because all these glides will have the same DOM structure, but you will probably want a different way to uniquely refer to the individual glide, so that you can ensure that the bullets are controlling the correct glide.

```
const glides = document.querySelectorAll( '.glide' );

glides.forEach( glide => {
	const parentId = glide.parentNode.parentNode.parentNode.id;
	const thisGlide = new Glide( '#' + parentId + ' .glide' ).mount();
	const bullets = document.querySelectorAll( '[data-glide-parent="' + parentId + '"] .glide__bullet' );

	bullets.forEach( bullet => {
		bullet.addEventListener( 'click', e => {
			const slide = bullet.getAttribute( 'data-glide-dir' );
			thisGlide.go( slide );
		} );
	} );
} );
```

markup:
```
<div id="tabbed-images-block_5f737aa0e3fe8" class="tabbed-images wp-block-acf-dogooddesign-tabbed-images">
    
    <div class="wp-block-columns">

        <div class="wp-block-column" style="flex-basis:60%">

            <div class="glide glide--ltr glide--slider glide--swipeable">

                <div class="glide__track" data-glide-el="track">

                    <ul class="glide__slides">
                        
                        <li class="tabbed-images__image-wrap glide__slide glide__slide--active">
                            Slide content.
                        </li>
                        
                        <li class="tabbed-images__image-wrap glide__slide">
                            Slide content.
                        </li>

                    </ul>

                </div>

            </div>

        </div>

        <div class="wp-block-column" style="flex-basis:40%">

            <div class="glide__bullets" data-glide-parent="tabbed-images-block_5f737aa0e3fe8">

                <div class="tabbed-images__tab-control glide__bullet" data-glide-dir="=0">
                    Bullet
                </div>

                <div class="tabbed-images__tab-control glide__bullet" data-glide-dir="=1">
                    Bullet
                </div>

            </div>

        </div>
    </div>
</div>
```
