### ISSUE TITLE
How to use glide__bullets outside of glide wrapper?

### ISSUE THREAD

**Issue by heliomsolivas** [glidejs/glide#211]
I'm trying to use the glide bullets in another div, outside of glide wrapper, it is possible?

**Comment by jedrzejchalubek** [comment]
Controls are only searched and binded inside a root element by quering `data-glide-el="controls"`. 

To create external controls you have to use an API.

**Comment by heliomsolivas** [comment]
@jedrzejchalubek resolved, thanks!

**Comment by Ceyar** [comment]
Hello, how did you resolve your problem?

Thank you
