### ISSUE TITLE
Documentation - Setup - ES Modules

### ISSUE THREAD

**Issue by guryanov-a** [glidejs/glide#212]
https://glidejs.com/docs/setup/#using-es-modules
1. "Explanation" link doesn't have an anchor so after click it just reloads the page
2. `import { Glide, Controls, Breakpoints } from '@glidejs/glide/dist/glide.modular.esm'` should be `import Glide, { Controls, Breakpoints } from '@glidejs/glide/dist/glide.modular.esm'` because `Glide` is a default import

**Comment by jedrzejchalubek** [comment]
Yes, this is how it should be. Corrected in https://github.com/glidejs/docs/pull/3

**Comment by guryanov-a** [comment]
> "Explanation" link doesn't have an anchor so after click it just reloads the page

is still relevant
