### ISSUE TITLE
Document browser support

### ISSUE THREAD

**Issue by pcvandamcb** [glidejs/glide#214]
I'm thinking of using this project for our new gallery, but I can't find any documentation on browser support. I tried the examples on glidejs.com in IE11 and Safari 9 for example, but the entire page does not seem to load at all.

Also for contributors it must be required to know which browsers code should support.

What is the official browser support on this library?

**Comment by jedrzejchalubek** [comment]
@pcvandamcb The website can have its own problems which are not related to glidejs script itself. Shame 🐼, but I do not do many tests.

I didn't make any comprehensive in IE, as I do not have an easy access to a Windows-based machine. Currently, these versions should be supported:
- IE11+
- Edge
- Chrome 10+
- Firefox 10+
- Opera 15+
- Safari 5.1+

It would be great if someone could test script out in different browsers. It would require to set up a simple sandbox, if anybody would be interested I can help with this.

**Comment by jedrzejchalubek** [comment]
Additional thought and note to myself: I think glide can support even IE 9+ on UMD builds with some small refactors (like switching `el.dataset` to `el.getAttribute`).

**Comment by IrinaShv** [comment]
Hi! It doesn't work in IE11. Error text: SCRIPT438: The object does not support a property or method "includes" in file glide.min.js.

**Comment by pcvandamcb** [comment]
Thanks for the reply!

I only tested the website examples. Will do more extensive testing of the actual library.

The includes error should be fixable by either adding a polyfill or swapping it out with an indexOf.

**Comment by jedrzejchalubek** [comment]
Great! I've already started preparations with 34f19b858dab32259436ccf6ef5add8e4bee20f0 and 5feafb29828f42eeeb6b64987d6eaab5efd0994d commits.

**Comment by jedrzejchalubek** [comment]
Now, with [`v3.0.4`](https://github.com/glidejs/glide/releases/tag/v3.0.4) release IE11 should be ok.

I've also added a list of the supported browser to the README.

**Comment by ishanisuchak** [comment]
Hi,
I can see a similar error on ie11 for "remove" method.
**Error text: SCRIPT438: Object doesn't support property or method 'remove'**
I have **version 3.1.0** installed in my solution.
Please let me know which version will have this bug resolved, if it has been resolved already.
