### ISSUE TITLE
Disabling looping (formerly circular: false?)

### ISSUE THREAD

**Issue by i-a-n** [glidejs/glide#219]
Hi there, thanks for maintaining this. Quick question: is there a way to disable looping at all? For example (ltr):

- when the slideIndex is 0, no left sliding
- when the slideIndex is at the last slide, no right sliding

Checking the old docs, it looks like this used to be possible with the option `circular: false`, but I don't see this in the current version. Is there another way to accomplish this? Thanks!

**Comment by gwidonw** [comment]
+1 for this feature.

I've tried to subscribe to `run.before` event and prevent changing slide for those cases but with no luck.

**Comment by i-a-n** [comment]
Do you have any immediate thoughts on how that would best be accomplished with the current API? I'd be happy to take a look and open a PR, so any ideas/guidance would be helpful.

**Comment by Shurov** [comment]
+1

**Comment by phts** [comment]
+1 - need this feature too.

**Comment by ppmazur** [comment]
@jedrzejchalubek Hi Jedrzej, is it possible to get this change in this week?

**Comment by jedrzejchalubek** [comment]
@i-a-n I appreciate help. Feel free to submit PR I'll help you there 👍 

The required changes should come down to simple `if` check in `Run.calculate` method (inside this sections: [run.js#L62-L66](https://github.com/glidejs/glide/blob/master/src/components/run.js#L62-L66) and [run.js#L78-L82](https://github.com/glidejs/glide/blob/master/src/components/run.js#L78-L82)). We should only overwrite `Glide.index` only when instance type is `slider` and new option named(?) `rewind` is set to true.

---

@ppmazur ¯\_(ツ)_/¯ It's open-source

**Comment by ppmazur** [comment]
Sorry, I didn't mean to be rude. I thought that you've already had the code for this change. My bad :)

**Comment by phts** [comment]
@jedrzejchalubek @i-a-n 
There is a PR: #223
