### ISSUE TITLE
Is there any way to prevent sliding?

### ISSUE THREAD

**Issue by adambartosiewicz** [glidejs/glide#221]
Hello!
I would like to navigate through slides only with nav buttons not with slide gesture (touch or mouse) as I would like to be able to slide content inside the slide. Is there any easy way to do it?
I haven't noticed any option to disable touch(slide) functionality.
Adam

**Comment by jedrzejchalubek** [comment]
There are two options that can help you `swipeThreshold` (for controlling touch swiping) and `dragThreshold` (for controlling mouse swiping). Refer to the [docs](https://glidejs.com/docs/options/).

However, if you using a modular build it's better to not to mount a `Swipe` component.

**Comment by christiankaindl** [comment]
@adambartosiewicz  I had the same problem and am using HTML script tags to import Glide. You can  disable the swipe by overriding the Swipe namespace:

``` js
const myGlide = new Glide('.glide')
myGlide.mount({
  Swipe: undefined
})
```

**Comment by annemacena** [comment]
> @adambartosiewicz I had the same problem and am using HTML script tags to import Glide. You can disable the swipe by overriding the Swipe namespace:
> 
> ```js
> const myGlide = new Glide('.glide')
> myGlide.mount({
>   Swipe: undefined
> })
> ```

ily
