### ISSUE TITLE
Work with react-router's <Link> ?

### ISSUE THREAD

**Issue by RoberMac** [glidejs/glide#222]
`<Link>` will be broken (like `<a>` reload page) after glidify.

**Comment by RoberMac** [comment]
I use modular import and mount without `Anchors` module, then it works. But Is there have a better way to do that?

**Comment by apuntovanini** [comment]
@RoberMac is right, I also tried an it works that way. Should we submit a PR @jedrzejchalubek?

**Comment by jedrzejchalubek** [comment]
@apuntovanini Of course! Would be really glad :)

**Comment by firestar300** [comment]
@RoberMac Did you do something like that ?

```javascript
<li className="glide__slide slide">
  <div className="slide__holder">
    <div className="slide__inner">
      <Link onClick={e => e.stopPropagation()} to="/single">My awesome Slide</Link>
    </div>
  </div>
</li>
```

I still have the problem.

**Comment by gja** [comment]
I spent 90 minutes debugging this exact issue. Thank you for fixing this!

**Comment by tienthanght96** [comment]
> I spent 90 minutes debugging this exact issue. Thank you for fixing this!

Did you fix this problem?
I tried to use glidejs version 3.4.1 in React project but it works incorrect when click <Link>: 
[Demo in codesandbox](https://codesandbox.io/embed/reverent-elion-fqtkk?fontsize=14&hidenavigation=1&theme=dark)
