### ISSUE TITLE
crashes browser if root element contains no children

### ISSUE THREAD

**Issue by bw1984** [glidejs/glide#224]
If you try to initialise glide (e.g. glide.mount) on an element which contains no children it causes the browser to crash (tested on both chrome and firefox). Presumably its caused by a memory leak. This is easily avoided once you're aware of it but took me a while to catch as all of our carousels are dynamically populated so thought i would raise it.

Might be worth adding in a small sanity check to prevent initialisation if there are no children

**Comment by jedrzejchalubek** [comment]
I understanding a problem, but as the core of the Glide is not aware of any HTML elements at mounting point (only components after mounting are), unfortunately, this does not come down to single sanity check :(

This should be checked by the developer itself before creating a new instance of Glide.
