### ISSUE TITLE
IE11 bug when destroying a carousel glide instance

### ISSUE THREAD

**Issue by casey6** [glidejs/glide#227]
When trying to call the `.destroy()` method on a carousel glide instance, IE11 will fail with an error saying _"Object doesn't support property or method 'remove'"_. This happens when trying to remove cloned slide DOM nodes.

Directly removing a DOM node with the [ChildNode.remove()](https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/remove) method is not supported in any version of Internet Explorer. While the [Node.removeChild()](https://developer.mozilla.org/en-US/docs/Web/API/Node/removeChild) method is supported all the way back to IE6.

**Comment by jedrzejchalubek** [comment]
Fixed with [v3.1.0](https://github.com/glidejs/glide/releases/tag/v3.1.0) release
