### ISSUE TITLE
[MAJOR BUG] Page infinite loops / crashes when .mount() is called before slides are on the page

### ISSUE THREAD

**Issue by Nickersoft** [glidejs/glide#232]
Hey guys!

I work frontend at https://www.udacity.com, and we're using Glide for carousels on some of our pages. I noticed that when `glide.mount()` is called before Angular can add slides to the page, the entire webpage crashes. This is because when creating clones Glide doesn't check to see if the length of the slides array is zero before dividing a number by it. If you divide by 0 in JS it results in Infinity, causing an infinite loop that will crash webpages. I added a check to prevent this and [opened a PR for it](https://github.com/glidejs/glide/pull/231). Would appreciate it if it could be looked at / merged as soon as possible, as this is a pretty major bug.

**Comment by jedrzejchalubek** [comment]
Fixed with [v3.1.0](https://github.com/glidejs/glide/releases/tag/v3.1.0) release

**Comment by ceb-luclin** [comment]
I get the same issue. Thankfully I found this post. When I pass an empty array initially it crashes the entire app forcing me to force quit the tab in Chrome's task manager.
