### ISSUE TITLE
glide js error on ie 11: Error text: SCRIPT438: Object doesn't support property or method 'remove'

### ISSUE THREAD

**Issue by ishanisuchak** [glidejs/glide#237]
I can see an error on ie11 for "remove" method.
**Error text: SCRIPT438: Object doesn't support property or method 'remove'**
I have version 3.1.0 installed in my solution.
Please let me know which version will have this bug resolved, if it has been resolved already.

**Comment by jedrzejchalubek** [comment]
Could you please paste what is in 438 line of your script?

**Comment by ishanisuchak** [comment]
```
...
append: function () {
                for (var e = this.items, n = this.pattern, o = 0; o < e.length; o++) {
                    var r = e[o];
                    r.style.width = t.Sizes.slideWidth + "px", "-" === n[o][0] ? t.Html.wrapper.insertBefore(r, t.Html.slides[0]) : t.Html.wrapper.appendChild(r);
                }
            }, remove: function () {
                for (var e = this.items, t = 0; t < e.length; t++)
                    e[t].remove(); ///This is where it errors out
            } };
...
```

**Comment by jedrzejchalubek** [comment]
The `v3.1.0` has fixed this issue. In this line should be an `removeChild` instead of `remove`: https://github.com/glidejs/glide/blob/v3.1.0/src/components/clones.js#L96

Please, double check if you really have `v3.1.0` installed.
