### ISSUE TITLE
Mounting with dynamic content fires error "Cannot read property 'classList' of undefined"

### ISSUE THREAD

**Issue by okatsuralau** [glidejs/glide#238]
A simple call to **`new Glide('.glide').mount()`** when there is no content (slides) breaks the page with an **`Uncaught TypeError: Cannot read property 'classList' of undefined`**.

Would be useful to be able to mount the Glide instance while waiting for an async content to be available or, at least, not triggering the error and breaking the entire page.

Currently, the only way to avoid this problem is to call the **`.mount()`** method manually only after the content has loaded and rendered correctly on the page.

**Comment by jedrzejchalubek** [comment]
> Currently, the only way to avoid this problem is to call the .mount() method manually only after the content has loaded and rendered correctly on the page.

This is how it should be done. Create a `Glide` instance earlier and mount it inside an async callback (when we have slides and glide can do calculations).

**Comment by skiokko** [comment]
+1 This error is still happening on latest version
