### ISSUE TITLE
transitionType: 'fade' not working

### ISSUE THREAD

**Issue by philmarc** [glidejs/glide#239]
```
new Glide('.glide', {
	type: 'carousel',
	gap: 0,
	autoplay: 8000,
	hoverpause: false,
	transitionType: 'fade'
}).mount()
```

I am trying to implement the fade effect, but it just keeps on sliding. Has it been removed?

**Comment by jedrzejchalubek** [comment]
Yes, a slideshow effect has been removed at v3.0.

**Comment by CorySchulz** [comment]
Would love to see fade added back in

**Comment by lukehatfield** [comment]
@CorySchulz checkout the CSS solution here, with one caveat about height: https://github.com/glidejs/glide/issues/279#issuecomment-468204570.
