### ISSUE TITLE
Auto populate bullets

### ISSUE THREAD

**Issue by projodesign** [glidejs/glide#241]
Assume there is a reason that the bullets have to be hard coded, rather than generated based on how many slides there are? Planning to use with a CMS where slides could be added or removed by a user. Fairly simple to implement my end, just wondered if you'd considered building it in?

**Comment by rishabh2712** [comment]
+1

**Comment by ebrahimpleite** [comment]
someone do?

**Comment by dukeatcoding** [comment]
Tried to implement a similiar solution for Angular 8 - also sturggeling to generate bullets.

But sadly it does not work
                            ```
  <div class="glide__bullets" data-glide-el="controls[nav]">
                          
                                    <div *ngFor="let bullet of bullets">
                                         <button class="glide__bullet" data-glide-dir="={{bullet.dir}}"></button> 
                                    </div>
                                </div>  
```

**Comment by gaetanvdberge** [comment]
I also needed the bullets to be dynamically generated. I counted the amount of items and added the bullets dynamically before I mount glide.js.

`function generateBulletsAndMountGlide() {
	var bulletCount = document.querySelectorAll('#carousel .glide__slide').length;
	var bulletWrapper = document.getElementById('glide__bullets');

	for (let index = 0; index < bulletCount; index++) {
		const button = document.createElement('button');
		button.className = 'glide__bullet';
		button.setAttribute("data-glide-dir", '='+index);

		bulletWrapper.appendChild(button)
	}

	glide.mount();
}
`

**Comment by cadday** [comment]
I have just modified @gaetanvdberge 's solution. It creates bullets and checks if they need to be shown based on the breakpoint.

`
// myGlide is a regular glide instance and d-none is a simple css class thats sets display:none;
// Appending max number of dots
myGlide.on(['mount.before'], function () {
  const bulletCount = myGlide.settings.perView;
  const bulletWrapper = myGlide.selector.querySelectorAll('.glide__bullets')[0];
  for (let index = 0; index < bulletCount; index++) {
    const button = document.createElement('button');
    button.className = 'glide__bullet';
    button.setAttribute("data-glide-dir", '=' + index);
    bulletWrapper.appendChild(button);
  }
});

// Hiding them with d-none if it is needed
myGlide.on(['resize', 'build.after'], function () {
  const perView = myGlide.settings.perView;
  const total = myGlide.selector.querySelectorAll('.glide__slide').length;
  const sub = total - perView;
  // Adds or removes d-none class
  myGlide.selector.querySelectorAll('.glide__bullet').forEach((el, i) => {
    if (i > sub) {
      el.classList.add("d-none");
    } else {
      el.classList.remove("d-none");
    }
  });

  // Prevents the empty last stop when resized for a larger breakpoint with more items
  if (myGlide.index > sub) {
    myGlide.go('=' + sub);
  }
});

myGlide.mount().update();`

**Comment by protherj** [comment]
This isn't quite correct.  The perView isn't the # of bullets, but rather "total slides" / perView.

The problem I'm having is that the bullets automatically are set to "active" by glide js incorrectly.  It is using the button number correlated to the slide number, but not the "view" number.  

I'll post code if I can get it working

**Comment by vladshestakov** [comment]
+

**Comment by davidlower8** [comment]
I thought I'd leave this code snippet for anyone trying to get this to work with wordpress/php.
`<div class="glide__bullets" id="glide__bullets" data-glide-el="controls[nav]">
                        <?php $testimonial_count = 0; ?>
                        <?php while ($testimonial_query->have_posts()) : $testimonial_query->the_post(); ?>
                            <button class="glide__bullet" data-glide-dir="=<?php echo $testimonial_count ?>"></button>
                            <?php $testimonial_count++ ?>
                        <?php endwhile; ?>
                    </div>`

**Comment by rinart73** [comment]
I made changes in the Control component.

```javascript
mount () {
  /**
   * Collection of navigation HTML elements.
   *
   * @private
   * @type {HTMLCollection}
   */
  this._n = Components.Html.root.querySelectorAll(NAV_SELECTOR)
  
  //Automatically create bullets
  const bulletWrapper = Components.Html.root.querySelector('.glide__bullets');
  if(bulletWrapper) {
    const fragment = document.createDocumentFragment();
    for(var index = 0; index < Components.Html.slides.length; index++) {
      var button = document.createElement('button');
      button.className = 'glide__bullet';
      button.setAttribute("data-glide-dir", '=' + index);
      fragment.appendChild(button);
    }
    bulletWrapper.innerHTML = '';
    bulletWrapper.appendChild(fragment);
  }

  /**
   * Collection of controls HTML elements.
   *
   * @private
   * @type {HTMLCollection}
   */
  this._c = Components.Html.root.querySelectorAll(CONTROLS_SELECTOR)

  this.addBindings()
},
```

I'm using `bulletWrapper.innerHTML = ''` to clear an optional placeholder bullet that could be used to prevent layout shift.
As a result my bullets HTML is:
```html
<div class="glide__bullets" data-glide-el="controls[nav]">
    <button class="glide__bullet"></button>
</div>
```

**Comment by andyjamesn** [comment]
I was able to use the get this working by extending the component as follows. @rinart73 code is spot on but instead of modifying the code its reworked to extend the Controls component as follows

``` Javascript
const autoBullets = function (Glide, Components, Events) {
    return {
        mount() {
            var NAV_SELECTOR = '[data-glide-el="controls[nav]"]';
            var CONTROLS_SELECTOR = '[data-glide-el^="controls"]';
            
            this._n =
                Components.Html.root.querySelectorAll(NAV_SELECTOR);

            //Automatically create bullets
            const totalSlides = Components.Html.slides.length;
            const bulletWrapper =
                Components.Html.root.querySelector(NAV_SELECTOR);
            if (bulletWrapper) {
                const fragment = document.createDocumentFragment();
                for (var index = 0; index < totalSlides; index++) {
                    var button = document.createElement('button');
                    button.className = 'glide__bullet';
                    button.setAttribute('data-glide-dir', '=' + index);
                    fragment.appendChild(button);
                }
                bulletWrapper.innerHTML = '';
                bulletWrapper.appendChild(fragment);
            }

            this._c =
                Components.Html.root.querySelectorAll(
                    CONTROLS_SELECTOR
                );

            Components.Controls.addBindings();
        }
    };
};
new Glide(this.DOM.el).mount({
    AutoBullets: autoBullets
});
```

**Comment by jedrzejchalubek** [comment]
Bullets auto-population will not be a part of the core of Glide. The way I can recomend is something proposed by @andyjamesn. You just need to mound your own extension.

**Comment by bastian-hidalgo** [comment]
No sense not putting bullets

> Bullets auto-population will not be a part of the core of Glide. The way I can recomend is something proposed by @andyjamesn. You just need to mound your own extension.

Theres no sense to implement an extension for a basic "slider/carousel"

**Comment by giantads** [comment]
Here is the full working code for auto bullets. This code is responsive, check the breakpoints perView number and works with bound:true as well :)

## Here is the initialization, what I used:
```
initializeGlide('#services-slider', {
    type: 'slider',
    bound: true,
    perView: 3,
    autoplay: false,
    animationDuration: 800,
    gap: 0,
    breakpoints: {
      992: {
        perView: 2,
        focusAt: 0,
      },
      576: {
        perView: 1
      }
    }
  });
```

## And here is the module with the auto navigations

```
import Glide from '@glidejs/glide';
import '@glidejs/glide/dist/css/glide.core.min.css';

export function initializeGlide(selector, options) {
  const sliders = document.querySelectorAll(selector);

  sliders.forEach(sliderElement => {
    const glide = new Glide(sliderElement, options);
    
    // Select elements
    const bulletsContainer = sliderElement.querySelector('.glide__bullets');
    const arrowsContainer = sliderElement.querySelector('.glide__arrows'); 
    const slides = sliderElement.querySelectorAll('.glide__slide');

    // Main function to update controls
    const updateControls = () => {
      const perView = glide.settings.perView; 
      const totalSlides = slides.length;
      const pageCount = Math.ceil(totalSlides / perView);

      // --- ARROWS ---
      if (arrowsContainer) {
         arrowsContainer.style.display = (totalSlides <= perView) ? 'none' : 'flex';
      }

      // --- BULLETS ---
      if (bulletsContainer) {
         bulletsContainer.innerHTML = ''; 

         // Hide if only 1 page
         if (pageCount <= 1) {
            bulletsContainer.style.display = 'none';
         } else {
            bulletsContainer.style.display = 'flex';

            for (let i = 0; i < pageCount; i++) {
               const button = document.createElement('button');
               button.className = 'glide__bullet';
               
               // Target index: Page 0 -> 0, Page 1 -> 2, etc.
               const targetIndex = i * perView;
               
               button.addEventListener('click', (e) => {
                   e.preventDefault(); 
                   glide.go(`=${targetIndex}`); 
               });
               
               bulletsContainer.appendChild(button);
            }
         }
      }
    };

    // --- SIMPLIFIED ACTIVE STATE LOGIC ---
    const updateActiveBullet = () => {
        if (!bulletsContainer) return;
        
        const bullets = bulletsContainer.querySelectorAll('.glide__bullet');
        const currentIndex = glide.index;
        const perView = glide.settings.perView;
        const totalSlides = slides.length;
        
        // Reset all
        bullets.forEach(b => b.classList.remove('glide__bullet--active'));

        let activeIndex = 0;

        // CHECK: Are we at the very end of the slider?
        // Logic: If current position + visible items >= total items
        // Example: Index 3 + 2 items >= 5 items -> TRUE -> We are at the end.
        const isAtEnd = (currentIndex + perView) >= totalSlides;

        if (isAtEnd) {
            // If we are at the end, ALWAYS select the last bullet.
            // This ignores whatever math mismatch 'bound: true' causes.
            activeIndex = bullets.length - 1;
        } else {
            // If not at the end, standard math applies.
            // Floor ensures that even if we are slightly offset, we stay on the current page.
            activeIndex = Math.floor(currentIndex / perView);
        }
        
        // Apply class
        if (bullets[activeIndex]) {
            bullets[activeIndex].classList.add('glide__bullet--active');
        }
    };

    // Listeners
    glide.on(['mount.after', 'resize'], () => {
        updateControls();     
        updateActiveBullet(); 
    });

    glide.on(['run', 'move.after'], updateActiveBullet);

    glide.mount();
  });
}
```
