### ISSUE TITLE
Added non-passive event listener to a scroll-blocking 'touchstart' event

### ISSUE THREAD

**Issue by antonlukin** [glidejs/glide#245]
Take a look at the Chrome warning, please.

> [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

Can be reproduced on glidejs.com with last Google Chrome browser.

**Env:**
macOS 10.13
Google Chrome 67.0

**Comment by jedrzejchalubek** [comment]
Should be fixed with [`v3.2.3`](https://github.com/glidejs/glide/releases/tag/v3.2.3) release.

**Comment by jedrzejchalubek** [comment]
Moving further discussion to https://github.com/glidejs/glide/pull/264
