### ISSUE TITLE
Swipe using mouse is broken in IE11 and MS Edge

### ISSUE THREAD

**Issue by Fender123** [glidejs/glide#248]
Since version 3.2.0 changing slides by swiping/dragging with the mouse is broken in IE11 and MS Edge.

It seems like these browsers don't get the mouseup or other events which stop the swiping mode. 
So it starts swiping as it should but it doesn't stop on mouseup. It continues moving/swiping on every mouse move event over the glidejs container.
You can also reproduce this on header slider on glidejs.com

Version 3.1.0 is working as expected. Therefore I think this commit broke it: https://github.com/glidejs/glide/commit/b3298009cf47d1f1ed9fb3e1edb08af9a5a2e723#diff-b12f136ed23be5d70c50cf9c81f26927

**Comment by mindhalt** [comment]
Same issue for me.

**Comment by jedrzejchalubek** [comment]
Should be fixed with [`v3.2.3`](https://github.com/glidejs/glide/releases/tag/v3.2.3) release.
