### ISSUE TITLE
Disable keyboard navigation

### ISSUE THREAD

**Issue by renandsgn** [glidejs/glide#250]
Hi, I  wanna know if have any way to disable de navigation with keyboard arrows, because when used with lightbox plugins have a lag in swipe...

**Comment by jedrzejchalubek** [comment]
There is a [`keyboard`](https://glidejs.com/docs/options/#keyboard-small-default-true-type-boolean-small-) option. Set it to false.

or if you are using modular build - do not mount a [`Keyboard`](https://glidejs.com/docs/components/keyboard/) component
