### ISSUE TITLE
Elements with Text are always Inline in a carousel

### ISSUE THREAD

**Issue by JonasJW** [glidejs/glide#254]
Until now I Glide worked very well but now I think I may found a Bug. 

I'm trying to have a carousel of a few Bootstrap cards with a picture and some text. The Problem is that the text is always inline.

The HTML of a Card looks like this:

<div class="">
    <div class="card">
        <img class="card-img-top" src="../../../assets/images/offer_1.jpg">
        <div class="card-body text-center">
    
            <h1>name</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias quam, sequi consequatur suscipit at temporibus corrupti quia</p>
            <h2>price€</h2>
        </div>
    </div>
</div>

And my Carousel HTML looks like this:

`<div class="glide" >
    <div data-glide-el="track" class="glide__track">
      <ul class="glide__slides" >
        <app-offer-item 
        *ngFor="let offer of offers"
        [offer]="offer"
        >
      </app-offer-item>
      </ul>
    </div>
  </div>`

I'm using Angular but I think this code should be understandable for non angular users. the `*ngFor` part is the equivalent of putting the Card HTML Code a few times inside the `<ul class="glide__slides">`

And it will look like this:

![image](https://user-images.githubusercontent.com/38528004/43767248-e8ac9fa8-9a34-11e8-9490-07266e8be8a7.png)

As you can see the paragraph is in one line. This behaviour occures only when using the carousel. When I use the cards without the carousel it does have line breaks and looks as it should. 

Is this a Bug or am I doing something wrong? How can I fix it?

-----------------------
For some reason the inserted code is not styled correctly and is cut off. Here are screenshots of it:

![image](https://user-images.githubusercontent.com/38528004/43767584-cd7357a8-9a35-11e8-82dc-3bca3865d0f0.png)

![image](https://user-images.githubusercontent.com/38528004/43767612-dd4dea44-9a35-11e8-976a-6a1b129fd955.png)

**Comment by jedrzejchalubek** [comment]
I think it is related to `white-space` CSS property; We already have PR (https://github.com/glidejs/glide/pull/249/files) which has been merged already but not released yet.

Can you apply corrected declaration and confirm if this helps?

**Comment by JonasJW** [comment]
I have changed `white-space` from `initial`to `normal` in `node_modules/@glidejs/glide/src/assets/sass/glide.core.scss`. Is that what you meant by apply declaration? Sadly that didn't solve it.

**Comment by JonasJW** [comment]
Any further Information? Is that actually a bug or am I doing something wrong? I really like this Library and want to use it but its impossible when I can't use text with it.
