### ISSUE TITLE
Click slide to advance to center position?

### ISSUE THREAD

**Issue by St3ve89** [glidejs/glide#260]
Such a great plugin, thanks.

In center mode, it would be nice to be able to click on a visible slide to promote it to the active position. Can you suggest an approach for this?

**Comment by oemueller** [comment]
you could simply listen to 'click' events of your slides and call the go($index) function of your glide instance.

**Comment by St3ve89** [comment]
I think, is not that simple with the clones unfortunately.

**Comment by oemueller** [comment]
It might work with data attributes:
https://codepen.io/oemueller/pen/YjowaK?editors=0100

**Comment by naaadz** [comment]
We would like it to scroll to the clone, not to the slide, in order for the glide to appear natural.  The .go method doesn't natively do this.  Has anyone found a solution to this?

Thanks!

**Comment by AZRckCrwler** [comment]
I'm curious as to why this was closed, I am also trying to achieve this functionality. I'm experiencing the same problem mentioned above that is due to the clones.

**Comment by AZRckCrwler** [comment]
As a workaround, I added a `data-index=""` to each slide element, with respective zero-based index set.

Then this javascript. A possible improvement would be to wrap the loop in an eventListener that triggers off Glidejs' 'mount.after' event.

`
glide.mount(); // Mount must run first, or trigger loop below from 'mount.after' event.

let slides = document.querySelectorAll('.glide__slide');
for (let slide of slides) {
    slide.addEventListener('click', function () {
        let active = document.querySelector('.glide__slide--active');
        let target = this;
        let activeId = active.dataset.index;
        let targetId = target.dataset.index;
        let cloneClass = target.classList.contains('glide__slide--clone');
        
        if (targetId > activeId && cloneClass) {
            glide.go('<');
        } else if (targetId < activeId && cloneClass) {
            glide.go('>');
        } else if (targetId > activeId) {
            glide.go('>');
        } else if (targetId < activeId) {
            glide.go('<');
        }
    });
}
`

**Comment by Martskin** [comment]
Thanks @AZRckCrwler for sharing your solution! It helped me get mine working. I managed to add `data-index` to the slides and clones programmatically after mount:

``` js
// https://glidejs.com/docs/extending-components/
var CarouselComponent = function (Glide, Components, Events) {
        var carousel_keyword = {
          onMountAfter: function() {
            function gotoSlide(el, target_slide_index) {
              var is_cloned_slide = el.classList.contains(Glide.settings.classes.cloneSlide);
              var direction = target_slide_index > Glide.index ? '>' : '<';
              
              if (is_cloned_slide) {
                direction = target_slide_index > Glide.index ? '<' : '>'
              }

              if (!el.classList.contains(Glide.settings.classes.activeSlide)) {
                Glide.go(direction);
              }
            }

            Array.prototype.forEach.call(Components.Html.slides, function(el, i) {
              el.dataset.index = i;
              el.addEventListener('click', function() {gotoSlide(this, i)});
            });

            Array.prototype.forEach.call(Components.Clones.items, function(el, i) {
              var slide_index = i < Glide.settings.perView
                              ? Math.abs(i - (Glide.settings.perView + 1))
                              : i - Glide.settings.perView;

              el.dataset.index = slide_index;
              el.addEventListener('click', function() {gotoSlide(this, slide_index)});
            });
          },
          onRun: function() {
            // https://glidejs.com/docs/components/controls/

            // This sets the active class immediately on control clicks.
            Components.Controls.setActive();

            Array.prototype.forEach.call(Components.Html.slides, function(el) {
              el.classList.remove(Glide.settings.classes.activeSlide);
            });

            Components.Html.slides[Glide.index].classList.add(Glide.settings.classes.activeSlide);
          }
        }

        Events.on('mount.after', function () {
          carousel_keyword.onMountAfter()
        })
      
        Events.on('run', function () {
          carousel_keyword.onRun()
        })
      
        return carousel_keyword
      }

      new Glide('.glide', {
        type: 'carousel',
        startAt: 0,
        perView: 3,
        focusAt: 'center',
        gap: 0,
        breakpoints: {
          992: {
            perView: 1
          }
        }
      }).mount({
        'CarouselComponent': CarouselComponent
      });
```

**Comment by zeocs** [comment]
The solutions here didn't work for me for some reason. I ended up solving the task with my own approach and figured I'll share my code for anyone who might want to use it.

```
'MoveTowardsClicked': function(Glide, Components, Events) {
    var component = {
        onMountAfter: function() {
            function gotoSlide(clickedSlide) {
                const curSlide = Components.Html.slides[Glide.index];
                const allSlides = Array.prototype.slice.call(
                    Components.Html.root.querySelector('.glide__slides').children
                );
                const clickedSlideIdx = allSlides.indexOf(clickedSlide);
                const curSlideIdx = allSlides.indexOf(curSlide);

                if (clickedSlideIdx !== curSlideIdx) {
                    Glide.go(clickedSlideIdx > curSlideIdx ? '>' : '<');
                }
            }

            Array.prototype.forEach.call(Components.Html.slides, function(el, i) {
                el.addEventListener('click', function() { gotoSlide(this) });
            });

            Array.prototype.forEach.call(Components.Clones.items, function(el, i) {
                el.addEventListener('click', function() { gotoSlide(this) });
            });
        }
    };

    Events.on('mount.after', function () {
        component.onMountAfter();
    });

    return component;
}
```

The approach is to figure out which index the current slide and the clicked slide are among all the slides, regardless of whether they're clones or not. Then you can infer easily whether to move left or right. You could extend this to move to the clicked slide rather than just moving towards it by calculating the difference between `clickedSlideIdx` and `curSlideIdx` and calling `Glide.go()` the respective number of times.
