### ISSUE TITLE
How do you debug the source of this plugin ? (Not really an issue)

### ISSUE THREAD

**Issue by gautamz07** [glidejs/glide#261]
Hi, 

how do you debugg this plugin , I.E. while you use rollup.js and babel , how do you debug the modules in ES6 ? i believe if you debug the glide.js file in the dist/ folder , you are essentially debugging the ES5 compiled code , but what if you want to debug the ES6 code in the src/ folder ? 

P.S. i am new to tools like babel/rollup, apologies for the noob question :D.

Thank you.

**Comment by jedrzejchalubek** [comment]
Most of the browsers do not support ES6 directly, so you have to transpile it to ES5 at the current moment. 

If there is an error in your ES6 source code you will be warned about it by rollup/webpack at transpilation.
