### ISSUE TITLE
Carousel keeps weird spacer on the right // moved to the right 20px

### ISSUE THREAD

**Issue by phifa** [glidejs/glide#266]
Thanks for the great plugin, I just started digging into it. 

Here is my code: 

*index.html*
```
<div class="glide">
    <div class="glide__track" data-glide-el="track">
        <ul class="glide__slides">
            <li class="glide__slide" style="background-image:url('http://unsplash.it/1000/400?random&blur&gravity=center')">
                <h1>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Mollitia, quos!</h1>
            </li>          
            <li class="glide__slide" style="background-image:url('http://unsplash.it/800/400?random&blur&gravity=center')">
                TEST
            </li>
            <li class="glide__slide" style="background-image:url('assets/img/slider/4.jpg')">
                TEST
            </li>
        </ul>
    </div>
    <div class="glide__arrows" data-glide-el="controls">
        <button class="glide__arrow glide__arrow--left" data-glide-dir="<">prev</button>
        <button class="glide__arrow glide__arrow--right" data-glide-dir=">">next</button>
    </div>
</div>
```

*app.scss*
```
@import "node_modules/@glidejs/glide/src/assets/sass/glide.core";
@import "node_modules/@glidejs/glide/src/assets/sass/glide.theme";

.glide__slide {
  background-size: cover;
  width: 100%;
  height: 400px;
}

```

*app.js*
```
import Glide, {
  Controls,
  Breakpoints,
  Swipe
} from "@glidejs/glide/dist/glide.modular.esm";

new Glide(".glide", {
  type: "carousel",
  gap: 0
}).mount({ Swipe, Controls, Breakpoints });
```

As you can see in the image, there is a spacing on the left. What am I missing? I want the slides to be simply 100% width. When I slightly swipe over to the left, it looks like the image actually has 100% width, but is moved to the right around 20px, if that makes sense? 

<img width="671" alt="screenshot" src="https://user-images.githubusercontent.com/3061129/44427146-f808cc80-a590-11e8-92b4-111ecc8de5d1.png">

This is my temporary fix, but I obviously am missing sth: 

```
.glide__slide {
  transform: translateX(-20px);
}

```

**Comment by jedrzejchalubek** [comment]
I cannot help you without some sandbox that reflects the problem, as this is a heavily styles related issue.

My blind guess is that something with CSS reset/normalization is off. Take a look if `<ul>` element doesn't have any margin or padding.

**Comment by mostafamohamady** [comment]
Thanks for the great plugin,  I have problem when  insert  padding and margin between  <li class="glide__slide "> </li>   what is the best way to insert space between it  and does not happen spacing to first and last <li> ?
![image](https://user-images.githubusercontent.com/43729969/62827075-5545c580-bbc8-11e9-99fe-89099b3a0d55.png)
