### ISSUE TITLE
Transition classes for next slide

### ISSUE THREAD

**Issue by kieraneglin** [glidejs/glide#275]
We're trying to "feature" the active slide by making it 20% bigger than the other slides (similar to [this carousel](https://mixer.com/), but with smooth transitions).

In order to smoothly transition, it'd be great to have a class on the element we're moving to as well as an indication that a transition is occurring.  Is there any way to do this within Glide currently?  If not, that's a feature I'd love to see

**Comment by connorwilsonexceleron** [comment]
I'd also like to see if this would be possible! I'm trying to see if there is a way to use an event to apply classes, but its a bit troublesome

**Comment by connorwilsonexceleron** [comment]
So I've been looking at the component extension documentation and using the Coverflow example in the website homepage. Using that as a guide I kind of came up with this pseudocode solution.

```js
beforeAnimation: {
	pauseAnimation: () => {},
	fadeOutCurrentSlide: /* apply fade out class */,
	playAnimation: () => {},
	fadeInCurrentSlide: () => {}
}
```

I'm thinking that the `fadeInCurrentSlide` function could really just be a simple css transition using `glide__slide--active` class.

Wondering if anyone else could lend some insight on how to move forward?

Either way I'm gonna keep noodling this...

**Comment by jedrzejchalubek** [comment]
You can easily manage a class that has `scale()` CSS on it inside one of the events like `run.after` and apply it to the current slide index
