### ISSUE TITLE
Cannot set width of carousel

### ISSUE THREAD

**Issue by protoEvangelion** [glidejs/glide#277]
My goal is a carousel that is **50% of the viewport**. When adjusting the `.glide` & `.glide__track` to 50% of the viewport, the carousel works as expected.

However, **the carousel items are 100% of the viewport.** The carousel items have text in them that extend passed `.glide__track` which means they will not wrap.

**_Is there a simple way to change the width of the carousel at the core level?_**

I noticed that the width is based off the `Html.root.offsetWidth` in the `Sizes` component.

```js
define(Sizes, 'width', {
  get () {
    return Components.Html.root.offsetWidth
  }
})
```

Here is my naive attempt to mutate the `Sizes` component with a custom component.

```js
const Width = function (Glide, Components, Events) {
  return {
    mount () {
      Components.Html.root.offsetWidth = '400px'
    }
  }
}

new Glide('.glide').mount({ 'Width': Width })
```

If changing the width at the core level is not possible I would be open to sending a PR 😄

**Comment by protoEvangelion** [comment]
Well the fix was quite simple!
I had padding on the `.glide` class.
Moving my padding from that class to `.glide__slide` fixes the issue!

**Comment by JevinSidhu** [comment]
@protoEvangelion When I attempt to change the width, I get `Cannot assign to read only property 'offsetWidth'`. Was there another way you found to change the width of the carousel?

**Comment by protoEvangelion** [comment]
It was just a padding issue, and I didn't end up going the route of trying to set the offsetWidth.
