### ISSUE TITLE
Glide.go() go to wrong slide if previous animation has not finished. 

### ISSUE THREAD

**Issue by akavato** [glidejs/glide#281]
I'am using glide on links hover like this: 
`const mainMenuLinks = Array.from(document.querySelectorAll('.services-container a'));
mainMenuLinks.forEach((el, index) => {
    el.addEventListener('mouseover', () => {
        firstGlide.go('=' + index)
    })
});`
If animationDuration: 0 it works well, but if i set it to 800 for example, and move pretty fast from 1 to 4 link, it shows me second or third slide, while my mouse is over 4 link.

**Comment by gautamz07** [comment]
@akavato this is the desired behavior i believe, but below is a very ugly workaround ( you can replace the jQuery code with JS ) ::-

`
let glideClickedIdx = 0;

_instance.on('run.after' , () => {
    checkLastClicked();
});

$('.slider__bullets > button' ).on('click' , function(){
    glideClickedIdx = $(this).index();
});

function checkLastClicked() {
    if( glideClickedIdx !== _instance.index ) {
        setTimeout(()=> {
            _instance.go( `=${glideClickedIdx}` );
        }, 50 );
    }
}
`
