### ISSUE TITLE
For development purpose can't i just import `index.js` from the src folder ?

### ISSUE THREAD

**Issue by gautamz07** [glidejs/glide#282]
Hey guys , Really like this plugin , i've worked on a few carousel plugins before , but this one seems really interesting , thanks for putting this up , I wanted to fork this project and create a few modifications.

I have a question though , for development purpose , can't i just import the index.js file from the src directory and work on that ? 

Currently i am importing glide.esm.js and it works fine , but what if i want to edit the source of the plugin , I.E. work on the development code instead of the compiled code ? I have been scratching my head on this for a few days , any help would be really appreciated.

Thank you.

**Comment by NoMaillard** [comment]
you would need to fork the project and then you would be able to use it as a normal npm project [see here](https://docs.npmjs.com/cli/install) to install a npm module from different sources

**Comment by jedrzejchalubek** [comment]
You can import an entry file directly from source code. It is actually quite useful and I use it to build quick sandbox env when developing the slider. It looks something like this:

```js
import Glide from './node_modules/@glidejs/glide/entry/entry-complete'

let glide = new Glide(document.querySelector('.glide'))
```
