### ISSUE TITLE
How to get the current slide index when using Glide with React ?

### ISSUE THREAD

**Issue by MimoJSRepo** [glidejs/glide#284]
I started using Glide recently , but I am having a problem with getting the current index ,
The way I am using Glide is to use 
`new Glid("Glid")`

inside `ComponentDidMount` and I am trying to set the state of  to be equal to the current slide index using 
`this.setState()` Methode , but it is always showing error because `this` is unknown here,

could you please provide me with some example how to get the index and assign it to the state?

I started to think it was not a good idea to use Glide with React , even that there is no examples online for this usage !!

**Comment by NoMaillard** [comment]
you can get the `Glide` instance like this : 
```js
let glide = new Glide(".glide")
```

after that you can use `glide` as you wish, and get the index like this `glide.index`
