### ISSUE TITLE
Get existing slider instance. 

### ISSUE THREAD

**Issue by skiokko** [glidejs/glide#299]
Currently seem only possible to interact with the slider only if you have access to the slider variable AAA.
Ex:   var AAA = new Glide("#target");

But is not possible to access it dynamically  from the DOM.
Ex.  $("#target").destroy();

Seem there is no way to interact with the slider if I don't have the original variable. This seem absurd but true.

**Comment by jedrzejchalubek** [comment]
True. You cannot access instance like it is possible in jQuery.
