### ISSUE TITLE
glide freeze page

### ISSUE THREAD

**Issue by multivoltage** [glidejs/glide#301]
I love this lib. Unfortunatly I have to work in an environment where the DOM come from external plugin. So not all time I can define my own DOM. 
In your tutorial you put the attention to element with attribute: "data-glide-el="track".
In some case in my DOM I have two or more childrens under this element (not only ul like the example). I notice that when I setup Glide in this dom, the page freeze.

**Comment by jedrzejchalubek** [comment]
Can you share with me your markup structure that causing freezes? 

This will may help me with identifying a problem.

**Comment by fawmi** [comment]
This issue still exists. It happens when there is no slide in the slider parent class.
A workaround is to test whether there are slides available before mounting the slider.
```
let sliderContainer = document.querySelector('.glide__slider')
let slideHasAtLeastOneChild = slide.querySelector('.glide__slide');
        if(slideHasAtLeastOneChild) {
            new Glide(sliderContainer, {
                type: 'carousel',
            }).mount();
        }
```
