### ISSUE TITLE
Infinite Carousel cloned element lose eventlisteners.(example video included)

### ISSUE THREAD

**Issue by rockmandash** [glidejs/glide#302]
Please see my recording [Video](https://www.youtube.com/watch?v=s_nswdxB2So&feature=youtu.be)
Infinite Carousel cloned element lose event listeners.
My workaround is not using carouse but slider. Which is ok by me.
I use Glide along with react. Maybe I did something wrong?
The code is nasty, I'm not going to put it here, feel free to close my issue.
But Glide is the only best carousel currently in modern JS world.
Other react carousel option has too many bugs. I've tried.

**Comment by jeissler** [comment]
I'm facing this issue recently as well where I defined a Vue click handler to go to the selected slide, but any of the clones getting clicked doesn't register an event. I would use the 'slider' option, but I don't like seeing blank spots at the end of the list. Any work arounds for this is appreciated. Thanks for GlideJS, btw!

**Comment by Jorenm** [comment]
Is this custom infinite functionality or am I missing an option to enable this?

**Comment by kanaabe** [comment]
I'm also blocked on this with React Components as slide elements. The issue seems to be that [`append`](https://github.com/glidejs/glide/blob/master/src/components/clones.js#L56) is simply cloning HTML elements so components/event listening on those elements don't work. Not sure that there's a simple workaround. The only thing I can think of is to overwrite the `append` method but I haven't tested it out.

@Jorenm I think what you're looking for is `type: 'carousel'` in the Glide options.

**Comment by drewrawitz** [comment]
Try putting your event listeners in the `mount.after` event. 

I was having the same issue where my lightbox wasn't initiating on any cloned elements, but after putting my `fancybox` initialization in that `mount.after` event, I was able to get it to work.

```
$(function() {
  const glide = new Glide('.glide', {
    type: 'carousel',
    perView: 2,
    gap: 20,
    peek: { before: 0, after: 200 }
  });

  glide.on('mount.after', function() {
    $('[data-fancybox]').fancybox({
      buttons: [
        'zoom',
        'slideShow',
        'thumbs',
        'close'
      ]
    });
  });

  glide.mount();
});
```

**Comment by italo1983** [comment]
Does not work with vanilla JS, cloned element lose click event.

`glide.on(['mount.after'], function() {
...
var ind = parseInt(target.getAttribute('data-index'))
glide.go('='+ind) ;
...
});
glide.mount();`

**Comment by opr** [comment]
Mounting carousel in a `useEffect` hook in react, cloned elements do not have any `onClick` functionality (original element works fine) any ideas?

Thanks

**Comment by EthianWong** [comment]
so, how to resolve this problem?

**Comment by jedrzejchalubek** [comment]
Not sure how it would be implemented in React, but I advise you to try with events delegation. In simple words add the event to a parent element, so it will not disappear after cloning and conditionally run login if the target is a desired element

```js
// declare handler
function clickHandler(e) {
  if (e.target.matches('.item')) {
    console.log(e.target.innerHTML);
  }
}

// reference to a list
const list = document.querySelector('.el');

// add a single listener on list item
list.addEventListener('click', clickHandler);
```

**Comment by mgalkus** [comment]
@jedrzejchalubek, in your code, where is the parent and where is the child? Also, could you target child elements that are removed from parent by several levels? Thanks!

**Comment by opr** [comment]
@mgalkus Events go up, through the DOM, so add the event listener to the glide track or something (something that won't be removed) and then you can get the event's target to work out which slide the event was targeted at. Great idea @jedrzejchalubek :)

**Comment by Enigama** [comment]
I have the same problem in Vue, when cloned slide not load some props inside.
`<vue-glade-slide>`
  `<component :props='data'>`
`</vue-glade-slide>`

**Comment by wade-wojcak** [comment]
Also had issues here in a React/Gatsby app. Went with the click handler solve above, just targeting the clones only. Not great but it worked.

**Comment by npoggenburg** [comment]
> Not sure how it would be implemented in React, but I advise you to try with events delegation. In simple words add the event to a parent element, so it will not disappear after cloning and conditionally run login if the target is a desired element
> 
> ```js
> function clickHandler(e) {
>   if (e.target.matches('.item')) {
>     console.log(e.target.innerHTML);
>   }
> }
> 
> const el = document.querySelector('.el');
> 
> el.addEventListener('click', clickHandler);
> ```

This is a big offtopic but this solved my case:

```
glide.on('mount.after', function() {
    GLightbox({selector: '[data-lightbox]'});
});
```

**Comment by jedrzejchalubek** [comment]
The cloned element will lose its event listeners and there is no way to pass it on cloning. The current implementation of infinity scrolling has this limitation. The solution her is to use event delegation that I described here: https://github.com/glidejs/glide/issues/302#issuecomment-539972682

Changing this implementation logic so slides are not cloned but changes their positions is on my roadmap

**Comment by alexisgrau** [comment]
You can use a system like this :
This code checks if a button is clicked inside an element and check if it's a clone or not. If it's a clone trigger a click on the real card's button (who had an event listener registered).

```
                const carouselContainer = document.querySelector('#carousel-cards-<?php echo esc_attr($id); ?>');
                carouselContainer.addEventListener('click', function(e) {
                    const clickedElement = e.target.closest('.carousel-card-button');
                    if (clickedElement && clickedElement.classList.length > 0) {
                        const isInClone = clickedElement.closest('.glide__slide--clone');
                        if (isInClone) {
                            e.stopPropagation();
                            e.preventDefault();
                            Array.from(clickedElement.classList).forEach(className => {
                                if(className == 'carousel-card-button'){ return; }
                                const originalElement = carouselContainer.querySelector(`.${className}:not(.glide__slide--clone .${className})`);
                                if(originalElement && originalElement !== clickedElement){
                                    originalElement.click();
                                    return;
                                }
                            });
                        }
                    }
                });
```
