### ISSUE TITLE
Add class to all perView active slides

### ISSUE THREAD

**Issue by shobson** [glidejs/glide#303]
Fairly new to this rotator but was wondering if there was a solution that I could use to add a common class to all the active perView slides in the rotator? As of right now I believe one class (glide__slide--active) gets added to the "first" active slide but was wondering if anyone had a solution to apply this too all visible perView slides at a time?

**Comment by elron** [comment]
I would like this feature too

**Comment by msmith7904** [comment]
This feature would really help me out right now.

**Comment by Eltyo** [comment]
I have wasted too many hours trying to replicate this feature by adding my own active class pre-transition, but to no avail - the clone slides are really screwing me over rn. Please add this feature <3

**Comment by Eltyo** [comment]
Okay I figured out a solution if anybody needs it:
```
  const getCloneIdx = (idx, numNormalSlides) => {
    const numCloneSlidesOnEachSide = glide.settings.perView + 1 
    let cloneIdx = null
    if (idx < numCloneSlidesOnEachSide) {
      cloneIdx = idx + numCloneSlidesOnEachSide
    } else if (idx >= numNormalSlides - numCloneSlidesOnEachSide) {
      cloneIdx = idx - (numNormalSlides - numCloneSlidesOnEachSide)
    }
    return cloneIdx
  }

  const getActiveSlideIndices = numNormalSlides => {
    const activeSlideIndices = []
    for (let i = 0; i < glide.settings.perView; i++) {
      const slideIdx = (glide.index + i) % numNormalSlides
      activeSlideIndices.push({
        normal: slideIdx,
        clone: getCloneIdx(slideIdx, numNormalSlides)
      })
    }
    return activeSlideIndices
  }

  const toggleActiveSlides = slidesContainer => {
    const normalSlides = slidesContainer.querySelectorAll(`:scope > :not(.${glide.settings.classes.cloneSlide})`)
    const cloneSlides = slidesContainer.querySelectorAll(`:scope > .${glide.settings.classes.cloneSlide}`)
    getActiveSlideIndices(normalSlides.length).forEach(idx => {
      normalSlides[idx.normal].classList.toggle('active')
      if (idx.clone !== null) {
        cloneSlides[idx.clone].classList.toggle('active')
      }
    })
  }

  const slidesContainer =  document.querySelector('#testimonials .glide__slides')

  toggleActiveSlides(slidesContainer)

  glide.on(['run.before', 'run'], () => {
    toggleActiveSlides(slidesContainer)
  })
```

This code assumes you've already defined the `glide` variable

**Comment by powerbuoy** [comment]
Here's another solution. I didn't modify the `.glide__slide--active` class rather added a new `.glide__slide--visible` class: https://github.com/glidejs/glide/issues/434

**Comment by helenb** [comment]
This would also be very useful from an accessibility point of view. I have some custom code to add `aria-hidden="true"` to inactive slides, and remove it from active ones. But if your `perView` setting changes there is no reliable way to get that information.

**Comment by JshGrn** [comment]
> Okay I figured out a solution if anybody needs it:
> 
> ```
>   const getCloneIdx = (idx, numNormalSlides) => {
>     const numCloneSlidesOnEachSide = glide.settings.perView + 1 
>     let cloneIdx = null
>     if (idx < numCloneSlidesOnEachSide) {
>       cloneIdx = idx + numCloneSlidesOnEachSide
>     } else if (idx >= numNormalSlides - numCloneSlidesOnEachSide) {
>       cloneIdx = idx - (numNormalSlides - numCloneSlidesOnEachSide)
>     }
>     return cloneIdx
>   }
> 
>   const getActiveSlideIndices = numNormalSlides => {
>     const activeSlideIndices = []
>     for (let i = 0; i < glide.settings.perView; i++) {
>       const slideIdx = (glide.index + i) % numNormalSlides
>       activeSlideIndices.push({
>         normal: slideIdx,
>         clone: getCloneIdx(slideIdx, numNormalSlides)
>       })
>     }
>     return activeSlideIndices
>   }
> 
>   const toggleActiveSlides = slidesContainer => {
>     const normalSlides = slidesContainer.querySelectorAll(`:scope > :not(.${glide.settings.classes.cloneSlide})`)
>     const cloneSlides = slidesContainer.querySelectorAll(`:scope > .${glide.settings.classes.cloneSlide}`)
>     getActiveSlideIndices(normalSlides.length).forEach(idx => {
>       normalSlides[idx.normal].classList.toggle('active')
>       if (idx.clone !== null) {
>         cloneSlides[idx.clone].classList.toggle('active')
>       }
>     })
>   }
> 
>   // Change this to your container
>   const slidesContainer =  document.querySelector('#testimonials .glide__slides')
> 
>   toggleActiveSlides(slidesContainer)
> 
>   glide.on(['run.before', 'run'], () => {
>     toggleActiveSlides(slidesContainer)
>   })
> ```
> 
> This code assumes you've already defined the `glide` variable

This only works if you are not using breakpoints
