### ISSUE TITLE
Webpack import not found

### ISSUE THREAD

**Issue by xavierfoucrier** [glidejs/glide#305]
Hi GlideJS team!

When using GlideJS with webpack 4.28 and **the modular dist**, the import of some modules fail like Gaps or Peek. Trying to import the Peek module:

```js
import Glide, {Autoplay, Breakpoints, Peek} from '@glidejs/glide/dist/glide.modular.esm.js';
```

throws: **warning "export 'Peek' was not found in '@glidejs/glide/dist/glide.modular.esm.js'"**

However the `Peek` function is present in the dist file :confused:

Thanks for your feedback!

**Comment by jedrzejchalubek** [comment]
Peek module is a required component and cannot be imported on demand. In other words, it is always included with Glide as it is required by the core of the slider.

Here are optional modules that can be imported only when they are needed: https://github.com/glidejs/glide/blob/master/entry/entry-modular.js#L39-L47

**Comment by xavierfoucrier** [comment]
Hi @jedrzejchalubek,

Thanks for your answer!

I just see that there is a "Usage: required" or "Usage: optional" on each module page, but it is not really so easy to see it: may be a `required` word specified near each required module in the **components aside list** on the documentation site should be better.

Nice slider BTW :wink:
