### ISSUE TITLE
Browser(s) offset the section where the carousel is until resized or dev tools are opened, then go back in place.

### ISSUE THREAD

**Issue by pecko95** [glidejs/glide#306]
Not sure if this is Glide.js related issue, or a general browser related issue, but as the title says all the browsers I have tested, offset the section where the carousel is being used for a few pixels, about 10px. And that remains until I resize the window's width or height even for 1px, or until I open the dev tools. Anyone other faced such an issue ?

**Comment by ValentinDelarue** [comment]
Hello, what was the problem?
