### ISSUE TITLE
Drag & drop is broken

### ISSUE THREAD

**Issue by marcwieland95** [glidejs/glide#311]
I just noticed that there's an issue even on the documentation page with the drag & drop.

The element is lost and can't be moved after some mouse interactions. I'm not sure on which exact behaviour this is happening.

Is this issue already known? For me, it looks like it's quite critical and a basic behaviour which sould work. I can dig into the code and debug. But first I wanted to hear if there are already some ideas on the issue.

Browser: Chrome 71.0 (but I tried also on other browsers)
OS: MacOS 10.14.2

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/6168975/52176194-7b208680-27af-11e9-983b-f0f5d348a6ed.gif)

**Comment by av01d** [comment]
Confirmed on Firefox 65 for OSX as well. And Chrome 72/OSX has the same problem, as does MS Edge on Windows.

**Comment by lifeinchords** [comment]
I think this is what I'm referencing as well in #309

**Comment by marcwieland95** [comment]
Did someone already some research regarding this issue? I'm using version 3 for the first time and I'm not familiar with the source code yet.

**Comment by jedrzejchalubek** [comment]
I've made some research about this issue and it looks like it may be caused by incorrect deletion of swiping events on dragging. `removeEventListener` do not receive the same capture argument as on `addEventListener`. Ref https://github.com/glidejs/glide/commit/cb74a3a134c9f2015d33ecfa733189bc4f744b18

Tagged new v3.2.6 release. It would be great if someone could give a test with this version.

**Comment by marcwieland95** [comment]
I can give it a try tomorrow.

**Comment by marcwieland95** [comment]
I updated GlideJS to versioh 3.2.6. But sadly I can't see any changes regarding the drag & drop issue.

![glidejs-slide-bug](https://user-images.githubusercontent.com/6168975/52614402-dcbcb100-2e91-11e9-8fa7-cbc419753352.gif)

**Comment by omares** [comment]
Our glide implementation has the same issue and i can reproduce it on the official glidejs documentation page

**Comment by omares** [comment]
I started to investigate the issue and it looks like this is related to the `moveable` [flag/logic inside swipe.js](https://github.com/glidejs/glide/blob/master/src/components/swipe.js#L24).

While testing i have seen that the flag is often [set to `false`](https://github.com/glidejs/glide/blob/master/src/components/swipe.js#L90) and thus preventing code [#1](https://github.com/glidejs/glide/blob/master/src/components/swipe.js#L81), [#2](https://github.com/glidejs/glide/blob/master/src/components/swipe.js#L116) from executing. Blatantly commenting out the [set to false](https://github.com/glidejs/glide/blob/master/src/components/swipe.js#L90) code seems to fix the issue.

The intention was to fix #258 but according to feedback it did not do so. My suggestion would be to remove the flag and code as it does not fix the issue and also introduces a component wide state which makes the code hard to understand and prone to side effects.

@jedrzejchalubek Would love to hear your opinion on my suggestion, as i gladly can/would apply the required changes.

**Comment by omares** [comment]
I am impatient and already created a PR #330 that includes my proposed change :)

**Comment by marcwieland95** [comment]
Thanks @omares for your pull request and your work fixing the bug by yourself.

I can confirm that the issue is fixed completely.

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/6168975/54827620-b79e3800-4cb2-11e9-9a1b-403958ccf113.gif)
