### ISSUE TITLE
Resize percentage based peek on window resize

### ISSUE THREAD

**Issue by sbrody** [glidejs/glide#313]
Hi
I've created a slider where 25% of the next slide peeks. This works fine until the window is resized - the amount of peek does not resize with the window. Is there a way to do this in Glide?
My basic code is below:
Thanks

var quarter = window.innerWidth / 4;
  
  var glideFeature = new Glide('.feature-glide', {
    peek: {
     before: 0,
      after: quarter,
      slideWidth: '75%'
    },

**Comment by carlosjunod** [comment]
I think there is a better way to do it.. but I achieved the expected behavior doing this:

```
let quarter = window.innerWidth / 4;
const myGlide = new Glide('.glide', {
  // ... your options
});


window.addEventListener('resize', function() {
  quarter = this.innerWidth / 4;
  myGlide.update()
})

window.addEventListener('load', function(){
  myGlide.mount()
})



```

**Comment by jedrzejchalubek** [comment]
Yep, need to update your `quarter` variable in `resize` event. Otherwise it contains value after of first pageload
