### ISSUE TITLE
Can't work if Glide Initialized before Vue.js init

### ISSUE THREAD

**Issue by adakbar** [glidejs/glide#332]
I just want to confirm, because this is odd. I have a simple javascript file that contain this.

```
import Glide from '@glidejs/glide';

new Glide('.glide', {
    type: "carousel"
}).mount();

const app = new Vue({
    el: "#app",
    data: {
        departureDate: null
    }
});
```

But Glide won't work, especially the next and previous button, but if I change it to.

```
import Glide from '@glidejs/glide';

const app = new Vue({
    el: "#app",
    data: {
        departureDate: null
    }
});

new Glide('.glide', {
    type: "carousel"
}).mount();
```

Then Glide works just fine.

**Comment by omares** [comment]
Hey @adakbar i am no Vue expert but looking at your code you are only initializing Vue itself, without any action happening. I would be very surprised if only that code causes glide to not work.

Do you get any JS error? Or can it bet that your remaining Vue code removes the glide html element?

**Comment by ericmorand** [comment]
@adakbar I assume it comes from the fact that initializing Vue remove the #app element from the DOM and the re-add it, thus removing all the event handlers that were present before Vue is initialized.

**Comment by omares** [comment]
Can this be closed?
