### ISSUE TITLE
Ability to remove event listeners

### ISSUE THREAD

**Issue by jamesmosier** [glidejs/glide#335]
Thanks for a great project! I was wondering if there was any ability (or workaround) to remove event listeners. For example:

```js
const glide = new Glide('.element');
glide.on('run.after', function() { ... });

// later on, clean up an event listener
glide.off('run.after');
```

The only way I have found has been to do something like this:

```js
element.removeEventListener('run.after', myEventHandlerFunc)
```

Thanks again!

**Comment by omares** [comment]
The `glide.on` method forwards its call to `EventBus.on` which would [return a callback](https://github.com/glidejs/glide/blob/master/src/core/event/events-bus.js#L35-L40) that enables you to remove the listener.

Unfortunately `glide.on` does not return that callback :(. Also changing the return logic of the method would  be an API break so i dont see high chances that this will happen easily.

You could [create an own component](https://glidejs.com/docs/extending-components/) and handle your logic in there. Each component gets the `EventsBus` injected giving you full access todo any magic you require.

**Comment by jamesmosier** [comment]
Thanks @omares!
