### ISSUE TITLE
Init only if window resize happens

### ISSUE THREAD

**Issue by acespace90** [glidejs/glide#336]
Hi I'm using Glide into tabs like this https://codepen.io/cferdinandi/pen/rRMJwK.

I have the slider in a tab, it doesn't work when I click in the specific tab where it is until I resize the browser window.

Can you help me solving this? 

Thanks in advice.

**Comment by nathanshanahan** [comment]
Wondering if you found a solve for this, running into a similar issue where slides only calculate correct width after resizing the browser window.

**Comment by jedrzejchalubek** [comment]
It is simple as calling `mount()` after you click into the specific tab. Glide cannot correctly calculate dimensions when it is in hidden on not existing until displaying content
