### ISSUE TITLE
Autoplay fires when one slide available

### ISSUE THREAD

**Issue by mkiesinski** [glidejs/glide#338]
I have set up glidejs to display a slider of recent posts 4 at a time. When there is only one post, the autoplay function slides it off screen and stops working. There should be a check for autoplay if there are enough elements to start.

Init code:
```       
new Glide(slider, {
   gap: 6,
   autoplay: 4000,
   type: 'slider',
   perView: 4,
   bound: true
}).mount();
````

After doing the autoplay, console throws this:
```
Uncaught TypeError: Cannot read property 'getAttribute' of undefined
    at Object.get (glide.esm.js:3447)
    at Object.start (glide.esm.js:3395)
    at eval (glide.esm.js:3394)
```

**Comment by levidps** [comment]
Is there a reason why you don't do a check before init glide.js? It would be as simple as check slide length.
