### ISSUE TITLE
Prevent overslide

### ISSUE THREAD

**Issue by equinusocio** [glidejs/glide#339]
Hi, is there a way to prevent the overscroll? The slider should not go over the current slides and stop after the last slide enter in viewport.

Check this gif:

![glide](https://user-images.githubusercontent.com/10454741/55728780-1387f100-5a15-11e9-9194-cd37a4b66453.gif)
:

This is my configuration:

```js
{
    type: 'slider',
    gap: 24,
    rewind: false,
    perView: 3,
    peek: {
      before: 156,
      after: 156
    },
    breakpoints: {
      960: {
        perView: 2
      },
      480: {
        perView: 1
      }
    }
}
```

**Comment by omares** [comment]
I would say the bound option does what you want. [Check out the documentation example](https://glidejs.com/docs/options/#bound-small-default-false-type-boolean-small-).
