### ISSUE TITLE
How to find out which way the slide went?

### ISSUE THREAD

**Issue by Polkovn1k** [glidejs/glide#349]
How to find out which way the slide went: to the right or to the left? My case: there are two identical sliders. I need to keep the same slides from showing at the same time. That is, if you change the slide of the first slider, this slide coincides with the slide from the second slider, it automatically scrolls to another +1 slide (if swiped to the right), or -1 (if swiped to the left).

**Comment by jedrzejchalubek** [comment]
There is a `run` event that tells you the current movement pattern. More here: https://glidejs.com/docs/events/
