### ISSUE TITLE
Is there a way to check number of slides?

### ISSUE THREAD

**Issue by igor-radivojevic** [glidejs/glide#354]
Is there a way to check how many slides I have in my slider?
I'm using a plain simple example.

```
this.glide = new Glide(this.glideEl.nativeElement, {
      type: 'slider',
      perView: 1,
      perTouch: 1,
      rewind: false,
});

this.glide.mount();
```

Currently I can do `this.glide.index` and get an index, but it would be nice if I could also do something like `this.glide.length` and get number of slides.

**Comment by igor-radivojevic** [comment]
Did a little trick with a custom component.

```
private Length(Glide, Components, Events) {
  return {
    mount() {
      Events.emit('length.change', Components.Sizes.length);
    }
  };
}
```
If anyone else just want to get length of sliders you can use this simple trick. And just listen to the event.

**Comment by apertureless** [comment]
Not sure if I made a mistake, but it's not working for me.

Codepen for reproduction:

https://codepen.io/apertureless/pen/gVaoNJ

The `console.log` gets fired. However not the emitted event.

**Comment by jedrzejchalubek** [comment]
You have to `mount()` slider after defining events https://codepen.io/anon/pen/voNRGK :)

**Comment by apertureless** [comment]
Thanks!
