### ISSUE TITLE
Start with left padding

### ISSUE THREAD

**Issue by tiagomatosweb** [glidejs/glide#363]
Hi, tks for the awesome plugin.

Is there a way to use carousel and center focused but with a left padding initially? like this website on "Why agencies choose us" section.

[https://www.storyblok.com/agencies](url)

Cheers tks

**Comment by andrei-dracea** [comment]
One way to do this is to place the slider in a container that has the left margin/padding set to what you wish and then, using css, set
```
.glide__track, .glide__slides { 
  overflow: visible; 
}
```
This way the slides are still visible as you go past them.

**Comment by tiagomatosweb** [comment]
Nice, I will test it when I back to the carousel component on our project and post here if it worked.
Thanks for sharing.

**Comment by tiagomatosweb** [comment]
Hello, here again and sorry for taking so long.
I didn't work quite well. Although it does the trick to the left side, it created a scroll to the right.

An example here https://jsfiddle.net/nu6dx598/1/.

Also I could do ```overflow-x: hidden``` in the body but I feel it is too hackie.

Any other idea?

**Comment by jedrzejchalubek** [comment]
It is an implementation problem. Closing, sorry 🙏
