### ISSUE TITLE
How to debug the plugin or add a new modification in ES6 src/ folder and test it (Not an issue , debugging help)

### ISSUE THREAD

**Issue by gautamz07** [glidejs/glide#377]
Hi , 

Thank you for the sleek plugin :) , just had a debugging question , ofcourse locally i can run an example of glide like so:

HTML code

```
<div class="glide">
    <div data-glide-el="track" class="glide__track">
        <ul class="glide__slides">
        <li class="glide__slide">
            <img src="img/1.jpg" alt="">
            <span>Slide 1</span>
        </li>
        <li class="glide__slide">
            <img src="img/2.jpg" alt="">
            <span>Slide 2</span>
        </li>
        <li class="glide__slide">
            <img src="img/1.jpg" alt="">
            <span>Slide 3</span>
        </li>
        </ul>
    </div>
</div>
```
JS code 

```
import Glide from '../dist/glide.esm.js';

new Glide('.glide').mount();
```

But what id like to know is how do i make modifications in the src folder and see if the source code works ? I mean how do you work while developing this plugin ?

**Comment by jedrzejchalubek** [comment]
If you have a proper bundling configuration, you can import an entry file and only run a building of you sandbox environment. 

This is how I personally do it. First, add `@glidejs/glide` dependency as path to a folder

```json
"dependencies": {
    "@glidejs/glide": "../glide"
}
``

Sandbox env has own Rollup configuration in place. Inside main js file I importing package directly from entry directory.

```js
// Complete import
import Glide from '@glidejs/glide/entry/entry-complete'
// Modular import
import Glide, { Controls, Breakpoints, Swipe } from '@glidejs/glide/entry/entry-modular'
```

**Comment by gautamz07** [comment]
@jedrzejchalubek , i used the following approach , added sourcemaps:true in the build/esm.modular.js file , problem is everytime i make a change in the source files , i have to run `npm run build:esm`

```
import build from './build'

export default Object.assign(build, {
  input: 'entry/entry-modular.js',
  output: Object.assign(build.output, {
    file: 'dist/glide.modular.esm.js',
    format: 'es',
    sourcemap : true   // added this line
  })
})
```

I'd be interested in knowing what modifications i'd have to make to which configuration to directly import `entry-modular` like you say ::-

`import Glide, { Controls, Breakpoints, Swipe } from '@glidejs/glide/entry/entry-modular'`
