### ISSUE TITLE
`this` error in isEnd/isStart methods of Components.Run 

### ISSUE THREAD

**Issue by vasylkorchynskyi** [glidejs/glide#378]
**@glidejs/glide: ^3.3.0**
I write component for custom controls ([here is gist](https://gist.github.com/vasylkorchynskyi/7be099b6669076f679089d8d8cca1ab0))
I want to disable prev button if `Glide.index === 0` and next one if `Glide.index === slides.length;`. I try to use Run component for this purpose, but get error `Cannot read property 'length' of undefined` - screenshot with error is below. 

`const start = isStart.bind(Glide); const end = isEnd.bind(Glide);` - resolve this issue, but seems a little badly. 

![image](https://user-images.githubusercontent.com/9628243/60027821-ddb6e800-96a6-11e9-8291-2c578cd828ca.png)

Is it bug in Run component or this component can't be used for that purpose?

**Comment by jedrzejchalubek** [comment]
You are loosing the `this` scope context when destructuring `Run` object. You have to operate directly on `Run` object or, as you did, bind() proper scope one again.

```js
const start = Components.Run.isStart();
const end = Components.Run.isEnd();
```

**Comment by vasylkorchynskyi** [comment]
That works. Thank you!
