### ISSUE TITLE
GlideJS not working on mobile

### ISSUE THREAD

**Issue by elieobeid7** [glidejs/glide#381]
I'm trying to add glidejs to a wordpress site, it's working perfectly on desktop, but on mobile, it's not loading, seems that the JS files aren't being executed. I don't see a single error in the console. [This the codepen][1]. On mobile I see 3 pictures on top of each other.

the template

    <section id="Glide" class="glide banner_desktop">
    
        
          <div class="glide__arrows">
            <button class="glide__arrow prev" data-glide-dir="<"><i class="fa fa-chevron-left fa-2x" aria-hidden="true"></i>
    </button>
            <button class="glide__arrow next" data-glide-dir=">"><i class="fa fa-chevron-right fa-2x" aria-hidden="true"></i>
    </button>
          </div>
    
    	 <div class="glide__wrapper">
            <ul class="glide__track">
    
    <?php if ( have_rows( 'banner_desktop', 'option' ) ) : ?>
    	<?php while ( have_rows( 'banner_desktop', 'option' ) ) : the_row(); ?>
    	<?php if ( get_sub_field( 'image' ) ) { ?>
    
    		  <li class="glide__slide">
    
    	<a href="<?php the_sub_field( 'link' ); ?>">
    					<img src="<?php the_sub_field( 'image' );?>" />
    				</a>				
    				</li>
    
    		<?php
    	}
    		 endwhile; endif;
    		 ?>
    
            </ul>
          </div>
          
          <div class="glide__bullets"></div>
    
    </section>

functions.php

    wp_enqueue_script( 'glide', get_bloginfo( 'stylesheet_directory' ) . '/js/glide/glide.js', array('jQuery') );
    wp_enqueue_script( 'glide_Js', get_bloginfo( 'stylesheet_directory' ) . '/js/glide/glide_JS.js', array('jQuery') );
    
    wp_enqueue_style( 'glide_css', get_bloginfo( 'stylesheet_directory' ) . '/js/glide/glide.css');
    wp_enqueue_style( 'glide_theme', get_bloginfo( 'stylesheet_directory' ) . '/js/glide/glide_theme.css');

glide.js is

    var glide = function () {
    // glide.min.js code which is on codepen 
    //   https://cdn.jsdelivr.net/npm/glidejs@2/dist/glide.min.js 
    }();

  [1]: https://codepen.io/usmonovsardor7770/pen/WEqjMa

**Comment by davidkhierl** [comment]
I think you should add the 4th argument on the enqueue script, make it true

**Comment by elieobeid7** [comment]
Tried that, didn't fix it, I'll have to find a way to make glide have a higher priority to load, I feel like the mobile browser forces the site to load quickly and what ends up happening is glide being the last to load, doesn't get a chance to do that.

**Comment by yankie9486** [comment]
If anybody runs into this error on WordPress. Adding the wp_add_inline_script worked for me.

`			wp_enqueue_script(
				'glide_js',
				URL . '/node_modules/@glidejs/glide/dist/glide.min.js',
				array(),
				VERSION,
				true
			);`

`			wp_add_inline_script(
				'glide_js',
				"window.addEventListener('DOMContentLoaded', function() {
var glide = new Glide('.glide');
				glide.mount();			
			});"
			);`
