### ISSUE TITLE
Installation by download issue

### ISSUE THREAD

**Issue by cseas** [glidejs/glide#383]
How do I run Glide without any npm installation? There are no instructions provided for it.

I'm trying to add a Glide carousel to a static website.

I've downloaded and referenced `glide.core.min.css` as a stylesheet and `glide.min.js` as a script but there is no effect on the example markup provided.

Can someone please provide a step by step instruction on which files to use and how to set it up for a simple static website?

Here's the below markup I'm using with no useful effect.

```html
<link rel="stylesheet" href="/assets/css/glide.core.min.css">
<link rel="stylesheet" href="/assets/css/glide.theme.min.css">
```

```html
<div class="glide">
  <div class="glide__track" data-glide-el="track">
    <ul class="glide__slides">
      <li class="glide__slide">0</li>
      <li class="glide__slide">1</li>
      <li class="glide__slide">2</li>
    </ul>
  </div>
</div>
```

```html
<script src="/assets/js/glide.min.js"></script>

<script>
  new Glide('.glide').mount()
</script>
```

**Comment by gautamz07** [comment]
Try this for initialization ::-

```import Glide from '../glide/dist/glide.esm.js';

let _instance = new Glide('.glide' , {
    type: 'slider',
    perView: 2,
    perViewC: 2, 
    bound: true,
    gap: 0,
    rewind : false,
    animationDuration: 200
}).mount();```

Also curious , what errors are you getting in the console ?

**Comment by cseas** [comment]
Turns out the code I originally posted was enough to make Glide working.

But the example code above that I took from the [Getting Started](https://glidejs.com/docs/setup/) docs only shows a "0" at the extreme left of the screen and nothing else. It was only when I click-dragged my mouse right to left that I realised the 0 changed to 1.

That example is really bad for a Getting Started tutorial. The docs should be updated to replace the getting started code with something that actually looks like a carousel to begin with, including a screenshot of what the result would be.

I found it very confusing that they showed beautiful examples at the site while the Docs have a starting example too minimal in contrast to even make the user realize it worked.

Here's the respective markup and screenshot of the result:
```html
<div class="glide">
  <div class="glide__track" data-glide-el="track">
    <ul class="glide__slides">
      <li class="glide__slide">0</li>
      <li class="glide__slide">1</li>
      <li class="glide__slide">2</li>
    </ul>
  </div>

  <div class="glide__arrows" data-glide-el="controls">
    <button class="glide__arrow glide__arrow--left" data-glide-dir="<">prev</button>
    <button class="glide__arrow glide__arrow--right" data-glide-dir=">">next</button>
  </div>

  <div class="glide__bullets" data-glide-el="controls[nav]">
    <button class="glide__bullet" data-glide-dir="=0"></button>
    <button class="glide__bullet" data-glide-dir="=1"></button>
    <button class="glide__bullet" data-glide-dir="=2"></button>
  </div>
</div>
```

![](https://user-images.githubusercontent.com/29686866/61077129-5fdf3480-a43b-11e9-8567-bf97d25e23e1.png)

**Comment by cseas** [comment]
Turns out the code I originally posted was enough to make Glide working.

But the example code above that I took from the [Getting Started](https://glidejs.com/docs/setup/) docs only shows a "0" at the extreme left of the screen and nothing else. It was only when I click-dragged my mouse right to left that I realised the 0 changed to 1.

That example is really bad for a Getting Started tutorial. The docs should be updated to replace the getting started code with something that actually looks like a carousel to begin with, including a screenshot of what the result would be.

I found it very confusing that they showed beautiful examples at the site while the Docs have a starting example too minimal in contrast to even make the user realize it worked.

Here's the respective markup and screenshot of the result:
```html
<div class="glide">
  <div class="glide__track" data-glide-el="track">
    <ul class="glide__slides">
      <li class="glide__slide">0</li>
      <li class="glide__slide">1</li>
      <li class="glide__slide">2</li>
    </ul>
  </div>

  <div class="glide__arrows" data-glide-el="controls">
    <button class="glide__arrow glide__arrow--left" data-glide-dir="<">prev</button>
    <button class="glide__arrow glide__arrow--right" data-glide-dir=">">next</button>
  </div>

  <div class="glide__bullets" data-glide-el="controls[nav]">
    <button class="glide__bullet" data-glide-dir="=0"></button>
    <button class="glide__bullet" data-glide-dir="=1"></button>
    <button class="glide__bullet" data-glide-dir="=2"></button>
  </div>
</div>
```

![](https://user-images.githubusercontent.com/29686866/61077129-5fdf3480-a43b-11e9-8567-bf97d25e23e1.png)

What markup should I use to get a carousel like the ones mentioned in [Options](https://glidejs.com/docs/options/)?

**Comment by gautamz07** [comment]
add a `<img src="" />` tag inside the `<li>` ?

**Comment by cseas** [comment]
That would just replace the numbers with the images specified. Still looks nothing close to the examples given on the Glide website. Below is the best I could get out of it after explicitly specifying a dark background:

![Selection_040](https://user-images.githubusercontent.com/29686866/61138937-fff19800-a4e5-11e9-9643-154c5db1e60d.png)

I've instead moved to Owl Carousel which works smoothly out of the box. Would still recommend the tutorials be updated to be more beginner friendly.
