### ISSUE TITLE
Is it possible to have controls outside of the `.glide` container?

### ISSUE THREAD

**Issue by andrecalvo** [glidejs/glide#391]
Wondering if I can use the `controls` markup outside of the `.glide` wrapper so it can be placed elsewhere on the page.

Thanks

**Comment by Jakeobr** [comment]
You can use a js "click" event listener to navigate through a slider using the .go() method. 
For example:
 
buttonNext.addEventListener("click", function(){
    yourSlide.go('>'); 
});

You can read about it here: https://glidejs.com/docs/api/
