### ISSUE TITLE
Problem when perView is larger than Slide-Amount

### ISSUE THREAD

**Issue by Juggern4ut** [glidejs/glide#397]
I've got a very simple slideshow using this code:
`new Glide(".detailslider-thumbs", {
    startAt: 0,
    perView: 6,
    bound: true
  }).mount()`

But in some cases the Slideshow contains less than 6 Slides. This doesnt seem to work, as I am still able to swipe through it, and somehow chaning the alignment from LTR to RTL... 

When I remove the bound-Option, I no longer have that problem, but I am able to scroll through the slides, until the last one is at position 0 which is not what I want either.

**Comment by madeinthearcade** [comment]
I came up with this problem too so as a workaround, I set `perView` by counting the number of slides I had.
```let numOfSlides = jQuery(element).find('.glide__slides').children('li'); 
perView: numOfSlides.length > 8 ? 8 : numOfSlides.length
```
