### ISSUE TITLE
When is the next release with slide view pagination coming out?

### ISSUE THREAD

**Issue by leonGiftagram** [glidejs/glide#400]
Hey Glide JS team!

Love what you guys are doing.  I use Glide JS and am very happy with it.  Wondering when the next release is coming out? From what I've read on https://github.com/glidejs/glide/pull/327 the next release will include slide view pagination.  So that arrow clicks and such will refresh/replace all slides in view.  Let me know!

Cheers,
Leon

**Comment by jedrzejchalubek** [comment]
👋 Hello, I've moved this feature to the next major 4.0 release along with a few other improvements that I have long wanted to introduce. 

Sorry about that!

**Comment by mahish** [comment]
The original PR looked great! Hope v4 is coming soon:)

**Comment by leonGiftagram** [comment]
Thanks @jedrzejchalubek and @mahish!  What is the option name for the glide pagination?

**Comment by jedrzejchalubek** [comment]
It has been released with v3.5.0
