### ISSUE TITLE
Pause ignored after hover

### ISSUE THREAD

**Issue by MarkHTML** [glidejs/glide#410]
Problem: Pause using the API: pause(), mouse over, mouse out and Glide starts sliding seeming without instruction.

I created a simple code pen, repeat the steps above: https://codepen.io/FlakCannon/pen/ExYbojN

Also this bug can be seen in the main documentation: https://glidejs.com/docs/api/#pause-

Sometimes it takes a few seconds but it always starts playing again.

**Comment by Striffly** [comment]
https://github.com/glidejs/glide/pull/439

**Comment by jedrzejchalubek** [comment]
Fixed with v3.5.0
