### ISSUE TITLE
Which Event to choose

### ISSUE THREAD

**Issue by jaafarassaf** [glidejs/glide#413]
I am trying to load images only when they are next to the active slide, so when I move to the next one I start updating the next 2 Images. 

therefore I was confused weither I should use the event run or move the get the most accurate index while swiping. 

With "move" I get to much answer while swiping, with run I get the definitive one but when you swipe too fast you only get the final one.

**Comment by jedrzejchalubek** [comment]
Based on your implementation you should use `run.before`, `run` or `run.after`
