### ISSUE TITLE
Style bullets like instagram

### ISSUE THREAD

**Issue by cylott** [glidejs/glide#418]
Has anyone successfully styled the bullets like instagram?

I'm not sure where to start because for whatever reason these elements are added manually to the DOM, so something would need to be done to animate them as the slides are flipped through.

I currently have some sliders with 30+ slides and the bullets do not scale gracefully.

Any help is much appreciated!

![IMG_E14F4ED6211B-1](https://user-images.githubusercontent.com/42451226/65579821-59863200-df2d-11e9-8bdd-e2774c15c1a5.jpeg)

**Comment by frankie-tech** [comment]
I couldn't get the animation to work, so they don't move from side to side. But I was able to get the bullets to change sizes properly.

[Repo](https://github.com/frankie-tech/instagram-bullets)

I'd love it if someone else could take a crack at it and get the bullet sliding animation

**Comment by wonderful123** [comment]
Here's the code that I implemented in ember.js and sass. You can easily get the logic out for plain javascript, etc.

Basically setting the class on each bullet and transforming unshown ones to 0 in size. Center the pagination and translate by percentage depending on how many bullets there are.

You can hook in to the 'run' method from glide.

**SCSS:**
`  .glide__bullets--active {
    background-color: none;
  }

  .glide__bullets {
    transform: translateX(0);
    transition: transform 300ms;

    .active {
      background-color: white;
      transition: background-color 300ms;
    }

    .inactive {
      transform: scale(0);
      transition: transform 300ms;
    }

    .small {
      transform: scale(0.8);
      transition: transform 300ms;
    }

    .smaller {
      transform: scale(0.4);
      transition: transform 300ms;
    }
  }`

**Ember.js**
`  @action
  registerGlide(element) {
    this.glide = new Glide(element.querySelector('.carousel'), {
      gap: 0,
    }).mount();

    this.glide.on('run', this.move);
  }

  @action
  move() {
    // Update active index of slide
    const currentIndex = this.glide.index;
    this.setBullets(currentIndex);

    // Translate by percentage depending on how many bullets
    const translate = currentIndex * (100 / this.imageCount);
    this.bulletsElement.style.transform = `translateX(-${translate}%)`;
  }

  @action
  setupBullets(element) {
    this.bulletsElement = element;
    this.bullets = element.getElementsByClassName('glide__bullet');
    this.setBullets(0);
  }

  @action
  setBullets(currentIndex = 0) {
    for (let i = 0; i < this.bullets.length; i++) {
      const bullet = this.bullets[i];
      bullet.classList.remove("inactive");
      bullet.classList.remove("active");
      bullet.classList.remove("small");
      bullet.classList.remove("smaller");

      if (i === currentIndex - 3 || i === currentIndex + 3) {
        bullet.classList.add("smaller");
      } else if (i === currentIndex - 2 || i === currentIndex + 2) {
        bullet.classList.add("small");
      } else if (i < currentIndex - 3 || i > currentIndex + 3) {
        bullet.classList.add("inactive");
      } else if (i === currentIndex) bullet.classList.add("active");
    }
  }`

**Comment by wonderful123** [comment]
Sorry about formatting, it didn't paste well

**Comment by wonderful123** [comment]
Also needs to offset center half a bullet wide.

```
const style = window.getComputedStyle(this.bullets[0]);
bulletOffset = parseFloat(style.width) / 2 + parseFloat(style.marginLeft) + 'px';
const translate = currentIndex * (100 / this.imageCount);
this.bulletsElement.style.transform = `translateX(calc(-${translate}% - ${this.bulletOffset}))`;
```

Damn things get complicated!
