### ISSUE TITLE
fixed image size with object-fit: contain

### ISSUE THREAD

**Issue by madeInLagny** [glidejs/glide#421]
I am using a slider with images of different sizes.
This is how it shows:

![image](https://user-images.githubusercontent.com/54598963/66206968-70edb980-e6a9-11e9-8a6a-b9b2df09ea3d.png)

I want the slider to resize all images at the same height (width can vary) and apply object-fit:contain.

Setting a height in css:

`img {height: 140px}`
works but is not responsive.

`img {height: 100%} `
also does not work.

Please advise on recommended approach.

**Comment by lifeinchords** [comment]
try
```
     .glide__slide {
         height: 140px;

        img {
            object-fit: cover;
            width: 100%;
            height: 100%;
        }

    }

```

you might also need to do 
```
.glide__slides {
        height: 140px;
}
```
