### ISSUE TITLE
Use glide in Alux Framework

### ISSUE THREAD

**Issue by afmarchetti** [glidejs/glide#422]
Hi i'm the author of Alux Framework:

https://github.com/afmarchetti/alux/

first of all, glide is amazing! super light :)

Can i use glide in my framework? obviously i will cite you as the author.

Many thanks,
Let me know,
Andrea

**Comment by jedrzejchalubek** [comment]
Of course! Feel free to use it 💯 Glide is licensed under the terms of the MIT :)
