### ISSUE TITLE
Is the HTML structure from the docs required?

### ISSUE THREAD

**Issue by ConduciveMammal** [glidejs/glide#432]
The documentation states that this is Glide's structure, but specifically mentions adding the track attribute. So if that's required, is the HTML class structure also required or is it just for example?

```html
<div class="glide">
  <div class="glide__track" data-glide-el="track">
    <ul class="glide__slides">
      <li class="glide__slide">0</li>
      <li class="glide__slide">1</li>
      <li class="glide__slide">2</li>
    </ul>
  </div>
</div>
```

**Comment by elliottregan** [comment]
Yes, it is.

**Comment by ericmorand** [comment]
Why? Why is glide depending on a data attribute and classes? It makes the HTML dependent on a JavaScript library.

We want to be able to write:

```js
<div class="my-slider">
    <div class="slides">
        <div class="slide">...</div>
        <div class="slide">...</div>
        <div class="slide">...</div>
    </div>
</div>
```

This way I control my classes and it makes my HTML markup non dependent on GlideJS.

**Comment by jedrzejchalubek** [comment]
Yes, it is required. Glide somehow needs to know what DOM elements need to query and it is done by data-attrs and proper HTML structure
