### ISSUE TITLE
Rewind slider at the next action after the last element is in the viewport

### ISSUE THREAD

**Issue by Darkecudoua** [glidejs/glide#437]
Hello,

Current configuration: slider, 6 per view, starts at 0, sliding one element per slide.

Currently the slider rewinds itself once you have the last element in the position 0. The problem is that until it reaches position 0, you slide..empty elements.

I would like to change this into: you slide, the last element gets in the viewport (is one of those 6 elements displayed in the view) and if you try to slide once more, as there are no elements left, to rewind you to the beginning.

Can something like this be achieved without rewriting the code base of the app?

Thank you

**Comment by MarkHTML** [comment]
+1

**Comment by Darkecudoua** [comment]
I missed that big time. Thank you @MarkHTML !
