### ISSUE TITLE
Glide JS website is not working

### ISSUE THREAD

**Issue by opr** [glidejs/glide#442]
When I try to access the glidejs.com site it errors for me ERR_SSL_PROTOCOL_ERROR - tried on different browsers and devices.

**Comment by mishaor** [comment]
It looks like it's been hacked by someone. On `http://` it redirects to `https://gab.justepl.com/f5232ef5-729b-4a9f-a872-bd81a8f3dc88?file=all-leads-matched-2019-11-30-2-3`. I've notified the author on Twitter.

**Comment by jedrzejchalubek** [comment]
I've been moving site to another hosting and make changes with DNS and nameservers.

Sorry for inconvenience :smile: Website is back now and wasn't hacked :sweat_smile:

**Comment by opr** [comment]
Great to hear :) thanks for such a great project
