### ISSUE TITLE
Problem with dynamically added slides

### ISSUE THREAD

**Issue by Kurzdor** [glidejs/glide#443]
Hi!
Thank you for library!
I have some problems with dynamically adding slides.
I am creating React wrapper for lib and I run into problem when adding new slides or removing and updating slider doesn't react to changes and doesn't add necessary styles, etc.
So if I have 5 numerated slides from 1 to 5 and after some timeout I add 6th slide and trying to run the update(options) method nothing happening.
How can this problem be solved?
Thank you in advance!

**Comment by jedrzejchalubek** [comment]
You need to run `update()` method in order to tell Glide that it has to recalculate dimensions
