### ISSUE TITLE
URL Hash Navigation

### ISSUE THREAD

**Issue by Ceyar** [glidejs/glide#447]
Hello, Is there a way to make a URL hash navigation like this plugin [Owl Carousel 2](https://owlcarousel2.github.io/OwlCarousel2/demos/urlhashnav.html)?

Thank you and best regards
Daniel

**Comment by janstieler** [comment]
Hi,
I have the same question. @Ceyar have you found a solution?

Thanks

**Comment by Ceyar** [comment]
Hey @janstieler Yes but you have to build yourself. For example your url is like this: https://myurl.com?slide-index=2. (it can be any custom param).

On load page check if there is a param in url and use it, use this param from your url and init Glide js with this param in the startAt param from Glide instance.

```
var glide = new Glide('#options-start-at', {
  startAt: yourIndexFromUrl,
  ...
})
```

Of course of each movement of your slide, you will have to update your url param with the correct index.

Let me know if it help you.
