### ISSUE TITLE
Problems adding 2 sliders

### ISSUE THREAD

**Issue by luislugop** [glidejs/glide#451]
I am adding two sliders in the same div, but when using one (the other one is cut in half), when updating I can use the second one (but the first one is trimmed), you have some example in script code, where you use 2 sliders in the same div?

**Comment by radiocity** [comment]
```js
const config = {
  type: 'slider',
  swipeThreshold: false,
};
const sliders = document.querySelectorAll('.glide');
sliders.forEach(el => {
  const uid = Math.random().toString(36).substring(7);
  el.setAttribute('data-uid', uid);
  const current = new Glide(`.glide[data-uid="${uid}"]`, config);
  current.mount();
});
```

**Comment by jedrzejchalubek** [comment]
https://github.com/glidejs/glide/issues/202
