### ISSUE TITLE
Problem interacting with a nav-tab and nav-pill

### ISSUE THREAD

**Issue by luislugop** [glidejs/glide#452]
The problem is: interacting with each of the tabs of "nav-tab (bootstrap)" there is no refresh between the tabs, which causes a library failure.
I have a nav-tab with 5 tabs, in the 5 tabs I wanted carousels, but when interacting with all of them, there is a problem of updating the carousels, (only until you interact with a carousel, you can visualize it well.)

**Comment by aningbo** [comment]
Did you resolve this problem? I'm facing the exact same issue.

**Comment by anitaparmar26** [comment]
Facing the same issue with the bootstrap 5 nav tab and pills.

**Comment by jedrzejchalubek** [comment]
You have to refresh/remount the slider on the tab change event in callback. The sliders inside tabs cannot be initialized as they don't exist in the DOM on the first load. That's why the first one works and all others don't.

**Comment by jedrzejchalubek** [comment]
Moving discussion here: https://github.com/glidejs/glide/issues/560
