### ISSUE TITLE
Changing width of slider items.

### ISSUE THREAD

**Issue by mazarady** [glidejs/glide#472]
Is there anyway to adjust the width of slide items?

**Comment by muuvmuuv** [comment]
I also would like to know that. I don't want to set `perView` just a width for each element.

**Comment by nitrokevin** [comment]
Variable widths would be great too

**Comment by whazlewo** [comment]
I came for this as well. I'm trying to make an interaction where one slide can temporarily expand, pushing the next slide over. I'm not sure if there is a way to do this at the moment.  Any ideas?

**Comment by stereochuck** [comment]
> I came for this as well. I'm trying to make an interaction where one slide can temporarily expand, pushing the next slide over. I'm not sure if there is a way to do this at the moment. Any ideas?

I'm not sure it's possible without any changes. You can probably fake it by using class toggling "glide__slide--active" and ccs animation and delays. But you know... it's the hard and messy way for sure.

**Comment by Braunson** [comment]
Same here, having an issue where the width of each slide is 100% the page width..

**Comment by mazarady** [comment]
Hey y’all. I never ended up finding a solution to this and opted for tiny slider.
