### ISSUE TITLE
latest version on npmjs.com doesn't equal master branch

### ISSUE THREAD

**Issue by SassNinja** [glidejs/glide#476]
I really need page navigation and was happy when I noticed there's already a merged PR for this https://github.com/glidejs/glide/pull/327

However it seems the published version on [npmjs.com](https://www.npmjs.com/package/@glidejs/glide) (3.4.1) does not equal the current master branch 

@jedrzejchalubek would you please publish it as 3.5.0?

**Comment by jedrzejchalubek** [comment]
Eventually, I had some time to look at the repo. Will release it soon 🤞
