### ISSUE TITLE
Can't initiate multiple sliders on same page.

### ISSUE THREAD

**Issue by antonstsk** [glidejs/glide#479]
Followed all the guides and responses to issues here, still ain't able to create multiple glidejs instances on same page.
While there's all fine having one instance, adding a new one seems to have conflict and just not able to understand what's happening, probably problem of scope or something.

> (No code provided because used standard template and forEach loop to initiate multiple instances)

![image](https://user-images.githubusercontent.com/33395021/79694568-58be4000-8271-11ea-902d-00d2deee657e.png)

**Comment by Fequois** [comment]
Hi @antonstsk! One solution to your problem would be to create a `NodeList` of your elements, and then loop through them and instantiate Glide on each.

See below for an example, and please ask if you can't get it to work.

```javascript
const sliders = document.querySelectorAll('selector');

sliders.forEach((slider) => {
  new Glide(slider).mount();
});
```

**Comment by antonstsk** [comment]
Hi @Fequois, thank you for your reply.
I'm sorry I didn't specify this earlier, but that's exactly what I did and that gave me the error from Glide source files.

**Comment by antonstsk** [comment]
@Fequois oh wait, I did said that I used simple forEach for initialization 😅

**Comment by Fequois** [comment]
Yeah, but I'm doing the above at this minute successfully and figured you might've done something differently.

Can you provide your HTML markup and JS please?

**Comment by antonstsk** [comment]
@Fequois sure, there's more images just simplified that because I'm using php to iterate over them.

Markup:
```html
<div class="container">
    <div class="tabs">
        <button class="active" data-tabs-tab="1">Gallery 1</button>
        <button data-tabs-tab="2">Gallery 2</button>
        <button data-tabs-tab="3">Gallery 3</button>
    </div>
    <div class="glide active" data-tabs-page="1">
        <div class="glide__track" data-glide-el="track">
            <div class="glide__slides">
                <div class="glide__slide">
                    <div class="image-wrapper">
                        <img src="gallery_1-image_1.jpg"/>
                    </div>
                    <div class="image-wrapper">
                        <img src="gallery_1-image_2.jpg"/>
                    </div>
                    <div class="image-wrapper">
                        <img src="gallery_1-image_3.jpg"/>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="glide active" data-tabs-page="2">
        <div class="glide__track" data-glide-el="track">
            <div class="glide__slides">
                <div class="glide__slide">
                    <div class="image-wrapper">
                        <img src="gallery_2-image_1.jpg"/>
                    </div>
                    <div class="image-wrapper">
                        <img src="gallery_2-image_2.jpg"/>
                    </div>
                    <div class="image-wrapper">
                        <img src="gallery_2-image_3.jpg"/>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="glide active" data-tabs-page="3">
        <div class="glide__track" data-glide-el="track">
            <div class="glide__slides">
                <div class="glide__slide">
                    <div class="image-wrapper">
                        <img src="gallery_3-image_1.jpg"/>
                    </div>
                    <div class="image-wrapper">
                        <img src="gallery_3-image_2.jpg"/>
                    </div>
                    <div class="image-wrapper">
                        <img src="gallery_3-image_3.jpg"/>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
```

Script:
```javascript
import Glide from "@glidejs/glide";

const initSlider = gallery => new Glide(gallery).mount();
document
	.querySelectorAll('.glide')
	forEach(initSlider);
```

**Comment by Fequois** [comment]
All I can say is it works for me, and that by the error above it looks like you aren't passing any elements to Glide. Wish I had a better answer. 🤷‍♂️

**Comment by antonstsk** [comment]
@Fequois as you can see in the stack trace it comes from inside of the plugin script although the file is `app.js`. (I'm concatenating them with webpack).
Don't worry, thanks for answering anyways.

**Comment by antonstsk** [comment]
@Fequois it seems that it doesn't work on `display: none` sliders. So they all must have height or something like that. Still figuring this out. Can't achieve to have multiple sliders and show them on tab changing. Maybe is there some king of filtering option?
