### ISSUE TITLE
Slides not correct width?

### ISSUE THREAD

**Issue by danielmonk** [glidejs/glide#480]
Hi,

I have created a slider seen here, I have set the perView to be 4 as I want 4 to be shown at all time, it cuts the 4th one off as they are too large for the container.

![Screenshot 2020-04-20 at 19 19 26](https://user-images.githubusercontent.com/13381680/79785915-8e7c2b00-833c-11ea-9f58-81f7de5a814a.png)

I have put an absolute width in the second photo to show the size they should be, but at the end there is big white space which is not needed.

![Screenshot 2020-04-21 at 09 53 45](https://user-images.githubusercontent.com/13381680/79846185-089cc600-83b6-11ea-8cf9-ab5cc6a59382.png)

how to fix this? I dont want the width overwritten and I dont want the white space.

**Comment by DoubleG-RUS** [comment]
https://glidejs.com/docs/options/#bound

**Comment by abstractpenguin** [comment]
While 'bound' would solve the large whitespace in the second screenshot, not showing all four slides in the first screenshot could be related to https://github.com/glidejs/glide/issues/210.
