### ISSUE TITLE
Change slide effect to fade effect?

### ISSUE THREAD

**Issue by Vince-vegas** [glidejs/glide#484]
Hi I'm trying to figured it out on how can i change the slide effect into Fade effect when i click buttons or autoplay it like SlickJs have

Can someone help me how can i change it to fade effect I'm using it on my Main Page

**Comment by markusguenther** [comment]
I disabled the animationDuration and used CSS to do that on my own.
Feels bit hacky but it works.

**Comment by frankie-tech** [comment]
Maybe this will help? https://github.com/glidejs/glide/issues/369#issuecomment-554668906 I've used it in the past, and its worked fine for me on v3

**Comment by jedrzejchalubek** [comment]
Duplicate of https://github.com/glidejs/glide/issues/369
