### ISSUE TITLE
Slide cropped

### ISSUE THREAD

**Issue by frenchqwerty** [glidejs/glide#489]
Hi,

I have a very strange issue with slider.

Sometimes, Glide display me 2 slides and the third is cropped like that :
![image](https://user-images.githubusercontent.com/19168177/81693459-37abd200-9460-11ea-8071-10f225a486ca.png)

I am working with Glide in v3.4.1.
The code be like : 
```
new Glide('.carousel-1', {
    type: 'slider',
    perView: 3,
    bound: true,
    startAt: 0,
    breakpoints: {
      767: {perView: 1},
      991: {perView: 2},
      992: {perView: 3}
    },
  }).mount();
```

**Comment by ezramod** [comment]
hy, found some solution? and me i have same problem

**Comment by jchck** [comment]
I ran into this bug as well & was able to resolve it by removing the browser's default right margin from the `ul.slider__slides` element.

Ex:
```
.slider__slides {
  margin-right: 0;
}
```
