### ISSUE TITLE
Cannot use multiple carousel in one page.

### ISSUE THREAD

**Issue by Sarthak001** [glidejs/glide#500]
any quick fixes ???

**Comment by PudottaPommin** [comment]
@Sarthak001 did you try to use different selectors for each glide? 
Try to set classes as 
Glide 1
```html
<div class="glide glide-1">...</div>
```
```js
const glide1 = new Glide('.glide-1');
glide1.mount();
```

Glide 2
```html
<div class="glide glide-2">...</div>
```
```js
const glide2 = new Glide('.glide-2');
glide2.mount();
```

**Comment by Sarthak001** [comment]
> @Sarthak001 did you try to use different selectors for each glide?
> Try to set classes as
> Glide 1
> 
> ```
> <div class="glide glide-1">...</div>
> ```
> 
> ```js
> const glide1 = new Glide('.glide-1');
> glide1.mount();
> ```
> 
> Glide 2
> 
> ```
> <div class="glide glide-2">...</div>
> ```
> 
> ```js
> const glide2 = new Glide('.glide-2');
> glide2.mount();
> ```

I tried the above solution. not working

**Comment by jedrzejchalubek** [comment]
Explained here: https://github.com/glidejs/glide/issues/202#issuecomment-382632126

**Comment by juanrapmc** [comment]
> Explained here: [#202 (comment)](https://github.com/glidejs/glide/issues/202#issuecomment-382632126)

so multiple carousel only works with .glide class?
