### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by febsn** [glidejs/glide#512]
There haven't been any commits for quite a few months, and there doesn't seem to be moderation on the issues.  @jedrzejchalubek is glide still being maintained?

**Comment by jedrzejchalubek** [comment]
@febsn I'm still here and will not abandon the Glide.js, but don't have much time for open-source work lately. Sorry about that!

**Comment by febsn** [comment]
That's great to hear, thanks a lot for your response!
