### ISSUE TITLE
Slide auto width

### ISSUE THREAD

**Issue by thebakerdev** [glidejs/glide#532]
Is there a way to replicate owl's slider auto width? https://owlcarousel2.github.io/OwlCarousel2/demos/autowidth.html 

I currently have a slider where one of the slides is twice as large as the others. Normally it would be resized evenly and make the larger slide squeeze.  

I've managed to make the slide width auto inside glide.on('build.after') & glide.on('run.after') but it messes up the slide animation and does not slide to the exact position of the slide. 

Is there any work around for this scenario?

**Comment by IrynaVynnychenko** [comment]
I have same question

**Comment by nickcartery** [comment]
I have the same issue :|

**Comment by jedrzejchalubek** [comment]
Currently, the `auto` size known from other slides is not a part of Glide. The moving logic expect slides to be the same width

**Comment by nicmare** [comment]
same question here!

**Comment by FranckPiazza** [comment]
Same request please some help :)
