### ISSUE TITLE
Glidejs does not display properly in the TAB menu

### ISSUE THREAD

**Issue by yaginkr** [glidejs/glide#539]
The first TAB of the slider can display properly, but on the other TAB can't display properly
You need the resizing browser window to make it normal

![Jan-15-2021 14-43-33](https://user-images.githubusercontent.com/68095981/104700246-36e9df00-5757-11eb-9a65-49a9d10f8d59.gif)

**Comment by aningbo** [comment]
Looks like this is a known issue which the developers don't care!! I'm facing the exact same issue with tabs.

Did you solve this?

**Comment by jedrzejchalubek** [comment]
You have to refresh/remount the slider on the tab change event in callback. The sliders inside tabs cannot be initialized as they don't exist in the DOM on the first load. That's why the first one works and all others don't.

**Comment by jedrzejchalubek** [comment]
Moving discussion here: https://github.com/glidejs/glide/issues/560
