### ISSUE TITLE
Glide doesn't work with Vue / id="app"

### ISSUE THREAD

**Issue by dnwjn** [glidejs/glide#545]
The main `div` inside `body` has `id="app"` set for Vue components that are used. If I try to use Glide with the id set, it doesn't work. It mounts, but that's it.

![image](https://user-images.githubusercontent.com/57711725/107678068-3b90ad00-6c9b-11eb-92d1-f131cde02c3e.png)

No sliding, no dragging, no clicking, no errors; nothing. If I take off the id, or if I comment out the Vue initialization code:

```
// const app = new Vue({
//     el: '#app',
// });
```

...or if I remove `.default` from the Vue require line:

```
- window.Vue = require('vue').default;
+ window.Vue = require('vue');
```

...it works.

My project is a Laravel 8 project. I have Glide.js configured like this:
1. `npm install @glidejs/glide`
2. Sass imports according to docs
3. Default structure according to docs
4. Bullet controls according to docs
5. Initialization as ES6 module

My dependencies are as follows:
```
    "dependencies": {
        "@fortawesome/fontawesome-free": "^5.15.1",
        "@glidejs/glide": "^3.4.1",
        "@tinymce/tinymce-vue": "^3.2.6",
        "axios": "^0.21.1",
        "bootstrap": "^4.5.3",
        "cross-env": "^5.2.1",
        "jquery": "^3.5.1",
        "laravel-mix": "^6.0.6",
        "lodash": "^4.17.20",
        "popper.js": "^1.16.1",
        "resolve-url-loader": "^3.1.2",
        "sass": "^1.27.0",
        "sass-loader": "^10.*",
        "tinymce": "^5.6.0",
        "tiptap": "^1.30.0",
        "v-click-outside": "^3.1.2",
        "vue-spinner": "^1.0.4"
    },
    "devDependencies": {
        "postcss": "^8.2.4",
        "vue": "^2.5.17",
        "vue-loader": "^15.9.6",
        "vue-template-compiler": "^2.6.10"
    },
```

The webpack config is as follows:
```
const mix = require('laravel-mix');

mix.js('resources/js/app.js', 'public/js')
    .vue()
    .sass('resources/sass/app.scss', 'public/css');
```

Any help is much appreciated!

**Comment by dnwjn** [comment]
I have run some more tests. `app.js` imports `bootstrap.js`, which includes the following line:

```
window._ = require('lodash');
```

When I comment out this line, the slider works too.

**Comment by OwenMelbz** [comment]
Are you initialising Glide **_AFTER_** vue has fully mounted? 

If you wrap your whole website in Vue, then Vue will read all the server-side generated HTML, load it into it's own VirtualDOM, then completely replace the whole website with a JS powered one.

This means if you are not initializing Glide AFTER Vue has fully done the replacement, then Vue will just overwrite everything like your code never ran.

**Comment by dnwjn** [comment]
> Are you initialising Glide **_AFTER_** vue has fully mounted?
> 
> If you wrap your whole website in Vue, then Vue will read all the server-side generated HTML, load it into it's own VirtualDOM, then completely replace the whole website with a JS powered one.
> 
> This means if you are not initializing Glide AFTER Vue has fully done the replacement, then Vue will just overwrite everything like your code never ran.

...do I feel dumb right now, but I'm not understanding this. I have many packages that I initialize **before** Vue initializes, and I haven't had any problems with those. In addition, I **have** tried your solution before, but I did not work back then.

So I don't know what caused the problem before, but since in the meantime the project has been cleaned up and packages have been updated I cannot trace it back...

Thanks anyways for your response, I have tried it in a fresh project and it did indeed work!
