### ISSUE TITLE
Carousel Build Completed Event - Run 1x?

### ISSUE THREAD

**Issue by sleblang** [glidejs/glide#562]
Is there an event that runs only once that tells when all items have been added to the carousel? Looking at the documentation, it does not appear one exists. I am having an issue where I am grabbing all the '.glide__slide:not(.glide__slide--active)') elements and adding a click handler to them. When these elements are clicked, the image shifts to the center.  However, the code that adds the click handler seems to be running too early and if I click the first image or last, the images don't shift. All other images will shift to the middle. If I add the code using a setTimeout to 1 second, then it works as expected. I would prefer to use some sort of listener or Promise if possible as depending on a setTimeout is not ideal. 

Thanks, in advance.

**Comment by jedrzejchalubek** [comment]
You should be able to use `build.after` event. At this point all classes generated by Glide are on its places
