### ISSUE TITLE
Change Autoplay Speed and Transition Type

### ISSUE THREAD

**Issue by thetacre8ive** [glidejs/glide#568]
Hi :-)
We are using PageFly Shopify Page Builder.
It has your slider.
But does not provide much control.

Is there a way to hook into and change properties, with js... to change the Auto Play Speed,,, and the Transition Type?

Note: We can not change the base code,,, but we can add in custom CSS and JS.

Thank you :-)
James

**Comment by thetacre8ive** [comment]
Hi :-)
No
Can u help?
Thx :-)

**Comment by jedrzejchalubek** [comment]
You can use options when initializing Glide instance to customize it. More here: https://glidejs.com/docs/options/
