### ISSUE TITLE
How to disable the loop?

### ISSUE THREAD

**Issue by alexanderkrupnitsky** [glidejs/glide#569]
I have not found a setting that stops cycling slides. How do I turn off the loop?

**Comment by frankie-tech** [comment]
I think you're referencing the `type` [option](https://glidejs.com/docs/options/#type).

The `'slider'` type will only go in one direction and then start over. The `'carousel'` type will loop all the slides.

```js
var slider = new Glide('#yourSlider', {
  type: 'slider', // will only go in one direction
});

var carousel = new Glide('#yourCarousel', {
  type: 'carousel', // will loop the slides with no 'rewind' or 'end'
});
```
