### ISSUE TITLE
Uncaught ReferenceError: Glide is not defined

### ISSUE THREAD

**Issue by adamskaiza** [glidejs/glide#571]
Hello,
After many problems to install and enqueue this package to wordpress, there is last one issue I cannot go thru.
Uncaught ReferenceError: Glide is not defined.

Way my js goes: 
let glideMulti = new Glide(document.querySelector('.multi'), {
    type: 'carousel',
    autoplay: 3500,
    perView: 3
});

glideMulti.mount();

EDIT:
Enqueued like this:
    //glide js

    function load_glide() {
      wp_register_script('load_glide', get_stylesheet_directory_uri() . '/node_modules/@glidejs/glide/dist/glide.min.js', array(), false, true);
      wp_enqueue_script('load_glide');
    }
    add_action('wp_enqueue_scripts', 'load_glide');
    

Can you help me, please?

**Comment by jedrzejchalubek** [comment]
Add dependency array to the `wp_register_script ` that loads your custom script where you initialize a `new Glide`. Your script loads before `glide.min.js`
