### ISSUE TITLE
Had to use an escape character "&gt;" for ">" in arrow button html

### ISSUE THREAD

**Issue by XanderCalvert** [glidejs/glide#572]
Minor issue I came across where I had to use an escape character in the code for the arrow button unlike what was used in the example on https://glidejs.com/docs/setup/.

` <button class="glide__arrow glide__arrow--right" data-glide-dir="&gt;">next</button>`

instead of 

` <button class="glide__arrow glide__arrow--right" data-glide-dir=">">next</button>`

Might help someone else if they come across this problem. Screenshot is what Chrome was rendering it as.

![image](https://user-images.githubusercontent.com/64328076/126968104-61ddc289-0769-4ecb-a856-50ed7f74be8f.png)

**Comment by jedrzejchalubek** [comment]
Thanks, looks like something related to the environment where HTML is deployed and how it parses it. Thanks for sharing!
