### ISSUE TITLE
Multiple instances of .glide not working with JS tabbed containers

### ISSUE THREAD

**Issue by Adamskoullos** [glidejs/glide#573]
Code:
```js
const sliders = [...document.querySelectorAll('.glide')];

  sliders.forEach(slider => {
    new Glide(slider, {
      type: "carousel",
      perView: 4,
      // focusAt: "center",
      breakpoints: {
        1600: {
          perView: 3,
        },
        1025: {
          perView: 2,
        },
        700: {
          perView: 1,
        },
      },
    }).mount();
  });
```

1. On initial load the default tabbed content shows the carousel..cool
2. When tabbing to further content the carousel for that content does not show
3. If the page is resized the carousel appears

I have read the article about using multiple instances, hense the code above, however this does not solve the problem of using a carousel for multiple tabs. Is there a solution for this ?

Thank you

**Comment by Adamskoullos** [comment]
Solved:

When switching between tabbed content each with a separate carousel, by disabling the old carousel and enabling the new carousel worked for me. Please let me know if this is bad practice...thanks

**Comment by Adamskoullos** [comment]
By enabling, I mean `slider.mount()`. Thanks

**Comment by digital-rama** [comment]
> abling the new carousel worked for me. Please let me know if this is bad practice...thanks
Hey, I'm also having the same problem. Can you please share the code?

**Comment by Adamskoullos** [comment]
Hey, since then different issues came up and in the end I pulled the plug and just built our own, specific to our needs. Sorry that's not what you were hoping for but hopefully I have saved you some time. Thanks
