### ISSUE TITLE
Handle resize

### ISSUE THREAD

**Issue by AlexisVK** [glidejs/glide#575]
Currently slides will not be updated if container will be resized. It updates only while window resizes. How can I add custom implementation to handle update with ResizeObserver API? Currently I don't have access to Size component methods

**Comment by jedrzejchalubek** [comment]
Yes, you can implement your own Size component and override the default one. You can use the build-in Sizes component as a base.

**Comment by Epizefiri** [comment]
Hi @jedrzejchalubek,
could you provide an example of how to use Size on resize?
