### ISSUE TITLE
Carousel with perView more than 1 shows empty spaces for other slides.

### ISSUE THREAD

**Issue by Nalin-2005** [glidejs/glide#578]
My Carousel looks something like this (images replaced)
![image](https://user-images.githubusercontent.com/54469875/132091766-83aac952-1337-4ba2-9aee-73625d3573f0.png)
but when it reaches the last slide, it looks like this:
![image](https://user-images.githubusercontent.com/54469875/132091756-9c6a41cc-7c9e-483a-9b26-53e07102008a.png)
which is not at all desired. Like in any other carousel, the first images should come and fill up the next spaces, but it does not happen here.

I used the `bound:true` option when creating the glide object, but that just loops after showing the second slide which does not actually solve the issue.

My HTML code (used with Next.js with the glide code in `componentDidMount` of the component for running it on the client side):
```jsx
<div className={styles.partnership_slider}><div data-glide-el="track">
  <ul>
    <li><Image alt="" src={Partner}/></li>
    <li><Image alt="" src={Partner}/></li>
    <li><Image alt="" src={Partner}/></li>
    <li><Image alt="" src={Partner}/></li>
    <li><Image alt="" src={Partner}/></li>
    <li><Image alt="" src={Partner}/></li>
  </ul></div>
  <div data-glide-el="controls" className={styles.partnership_slider_controls}>
    <button data-glide-dir="<" className={styles.partnership_slider_control_left}><i className="fas fa-chevron-left"></i></button>
    <button data-glide-dir=">" className={styles.partnership_slider_control_right}><i className="fas fa-chevron-right"></i></button>
  </div>
  <div data-glide-el="controls[nav]" className={styles.partnership_slider_bullets}>
    <button data-glide-dir="=0"></button>
    <button data-glide-dir="=1"></button>
    <button data-glide-dir="=2"></button>
    <button data-glide-dir="=3"></button>
    <button data-glide-dir="=4"></button>
    <button data-glide-dir="=5"></button>
  </div>
</div>
```
Code for glide:
```js
let glideOptions = {
  type: 'slider',
  perView: 5,
  breakpoints: {
    1000: {
      perView: 3
    },
    600: {
      perView: 1
    }
  },
  bound: true,
  autoplay: 4000
}
new Glide("."+styles.partnership_slider, glideOptions).mount()
```

**Comment by mauroreisvieira** [comment]
Hi, change the type to `carousel`

**Comment by Nalin-2005** [comment]
Oh. I think this was something really silly. Anyway, thanks for this.
