### ISSUE TITLE
setting getter-only property "slideWidth"

### ISSUE THREAD

**Issue by y1n0** [glidejs/glide#579]
Hello, I am trying to extending the Sizes Component to make the slides keep their intrinsic width. I tried to override the Sizes.slideWidth property but I get a `TypeError: setting getter-only property "slideWidth"`.

```js
const Example = function (Glide, Components, Events) {
	Events.on("build.before", () => {
		Components.Sizes.slideWidth = 480;
		// I also tried but I get the same error
		Components.Sizes.slideWidth = {
			get() {
				return 480;
			},
		};
	});
	return {
		mount() {
			console.log("mounted extension");
		},
	};
};

const glide = new Glide(ref.current, {
	type: "carousel",
	perView: items.length,
	focusAt: "center",
	peek: "50%",
	gap: 24,
});
glide.mount({ Example });
```

Can this be considered a bug? since the idea behind extending a component is to allow modify its values? How can I be change the width of slides?

Thanks

**Comment by jedrzejchalubek** [comment]
This error message is correct. You should not extend modules by directly mutate their properties. You need to prepare your entire own `Size` module and override the default one. Follow documentation how to create a custom module: https://glidejs.com/docs/extending-components/

You can always use a default one as a base and only change things that you need
