### ISSUE TITLE
How to autoplay smoothly without snap

### ISSUE THREAD

**Issue by openmindculture** [glidejs/glide#595]
I want to configure glide autoplay so that it does not stop at slides but rather moves them with continuous movement. Is this possible?

I tried setting a minimum `autoplay` interval, so that there would be no pause at each slide,
and a very long animation duration, so that it should take several minutes to complete the animation, thus making the animation very slow. 

```
  draggable.glide = new Glide(draggable, {
    type: 'carousel',
    gap: 24,
    startAt: 0,
    hoverpause: true,
    autoplay: 0,
    animationduration: 1000,
    direction: 'ltr',
    perView // set to the number of existing slide elements
  }).mount();
```

While the slow movement is a step in the right direction, no matter if I set `autoplay` to `1` or even `0`, the animation still stops at each slide. Also the animation does not start immediately but after a timeout, that I did not find how to override in the configuration.

Changing the `animationTimingFunc` also did not help me yet. What content should the `animationTimingFunc` be set to achieve a continuous motion?

**Comment by jedrzejchalubek** [comment]
Long story short: Possible but not recommended :) All details are here: https://github.com/glidejs/glide/issues/198#issuecomment-382634415

**Comment by openmindculture** [comment]
Thanks a lot! Apart from the UX considerations of carousels in general and the requirements, I will consider your performance warning. I like Glide's infinity implementation and also the draggable, swipeable behaviour and plain vanilla JS approach of Glide, but maybe it's not the best choice for that customer project then.
