### ISSUE TITLE
Build error (ES module) with node v16.15.0

### ISSUE THREAD

**Issue by julienchazal** [glidejs/glide#620]
Hello

Using last version of SvelteKit and node 16.15.0 i get this error : 

`(node:15002) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
Unexpected token 'export'`

adding `"type":"module"` to `node_modules/@glidejs/glide/package.json` fix the problem

**Comment by julienchazal** [comment]
@jedrzejchalubek is it possible to add this feature so that we can use Glide with newer versions of Node ?

please see [https://nodejs.org/api/packages.html#packagejson-and-file-extensions](https://nodejs.org/api/packages.html#packagejson-and-file-extensions)

thanks !

**Comment by jedrzejchalubek** [comment]
@julienchazal Are you open to making a PR with that change?

**Comment by julienchazal** [comment]
@jedrzejchalubek done

**Comment by julienchazal** [comment]
close with #623
